import type { KnowledgeNode } from "@/features/knowledge/types";
import { agenticNode as a, legacyAgenticNode as legacy } from "./demoKnowledgeNodeFactory.fixture";

export const agenticAiNodes: KnowledgeNode[] = [
  legacy("H01", "Agentic AI 全景", ["AG01", "H02", "H03"]),
  legacy("A05", "经典与现代 Agent", ["A01", "A02"]),
  legacy("R02", "ReAct 与推理循环", ["R01", "R10"]),
  legacy("R05", "规划、重规划与反思", ["R03", "R04", "R11", "R06", "R07", "R08", "R09"]),
  legacy("W05", "混合架构与 HITL", ["W01", "W02", "WF05"]),
  legacy("C05", "最小 Agent", ["C01", "C02", "C03", "C04"]),
  legacy("I03", "结构化输出与 Schema", ["I01", "I02", "I05"]),
  legacy("T01", "Tool Use / Function Calling", ["T11", "T12", "T03", "T14", "T15", "T06"]),
  legacy("T02", "Tool Schema", ["T11", "I02"]),
  legacy("T04", "Tool Failure / Retry", ["T07", "T08"]),
  legacy("T05", "副作用、权限与人工审批", ["T09", "T10", "W02"]),
  legacy("K02", "文档解析、Chunk 与 Embedding", ["K01", "K12", "K13"]),
  legacy("K03", "RAG 与引用", ["K14", "K15", "K16"]),
  legacy("RT04", "Runtime Limit / Recovery", ["RT03", "RT14"]),
  legacy("RT05", "Checkpoint 与审计", ["RT15", "RT06"]),
  legacy("W03", "Orchestrator–Worker", ["W13", "W04", "WF03"]),
  legacy("MA05", "Tool / Skill / Plugin / MCP / A2A", ["MA03", "MA04", "MA15", "MA06", "MA07"]),
  legacy("E02", "测试集与基准任务", ["E12"]),
  legacy("E03", "结果与轨迹评测", ["E13", "E14"]),
  legacy("E04", "可观测性与运行调试", ["E06", "E07"]),
  legacy("S04", "Guardrail 与权限", ["S01", "S02", "S03"]),
  legacy("S05", "API、数据库、队列与部署", ["S14", "S15", "S06", "S07", "S08"]),
  a("AG01", "Agent", "理解能感知状态、选择动作并朝目标推进的智能体。", "conceptual"),
  a("H02", "Workflow", "理解由显式步骤和控制关系组成的工作流。", "conceptual"),
  a("H03", "Automation System", "理解确定性自动化系统的能力边界。", "conceptual"),
  a("P01", "Task Environment", "描述 Agent 可观察、可行动的任务环境。", "representational"),
  a("P02", "Goal", "把用户意图表述为可推进的目标。", "representational"),
  a("P03", "Constraint", "表达任务执行过程中不得违反的限制。", "representational"),
  a("P05", "Completion Condition", "把自然语言要求转化为可检查的完成条件。", "procedural"),
  a("A01", "Classical Agent Architecture", "解释感知、决策、行动等经典智能体构件。", "conceptual"),
  a("A02", "LLM Agent Architecture", "解释模型、上下文、工具、状态与运行时的协作。", "conceptual"),
  a("R01", "Reasoning Loop", "组织可观察的推理、行动与反馈循环。", "meta"),
  a("R10", "ReAct", "交替执行 Reason、Act 与 Observation。", "procedural"),
  a("R03", "Planning", "在执行前形成有目标、有依赖的行动计划。", "meta"),
  a("R04", "Plan-and-Execute", "先生成可检查计划，再按步骤执行并收集结果。", "procedural"),
  a("R11", "Plan Monitoring", "比较计划预期与实际观察并识别偏差。", "meta"),
  a("R06", "Replanning", "根据新观察保留已完成步骤并调整剩余计划。", "procedural", [
    "能说明什么时候需要触发 Replanning",
    "能保留已完成步骤并修改剩余计划",
    "能根据新的 Observation 调整后续计划",
    "能区分 Replanning 与完整重新规划"
  ]),
  a("R07", "Reflection", "回顾执行轨迹并提炼可用于后续行动的改进。", "meta"),
  a("R08", "Evaluator", "使用明确标准判断输出或轨迹质量。", "meta"),
  a("R09", "Evaluator-Optimizer", "让 Evaluator 反馈驱动 Optimizer 迭代输出。", "procedural"),
  a("W01", "Human-in-the-loop", "在关键决策点引入人的判断和反馈。", "procedural"),
  a("W02", "Approval Gate", "在高风险动作前建立显式审批边界。", "procedural"),
  a("C01", "Agent Input", "定义 Agent 接收的任务输入和上下文入口。", "representational"),
  a("C02", "Model Invocation", "以受控参数调用模型并处理响应。", "procedural"),
  a("C03", "Agent State", "表示 Agent 一次运行中的持久和临时状态。", "representational"),
  a("C04", "Agent Output", "定义 Agent 对调用者交付的结果契约。", "representational"),
  a("I01", "Structured Output", "让模型输出满足机器可处理的明确结构。", "representational"),
  a("I02", "Schema", "定义字段、类型、约束和嵌套关系。", "representational"),
  a("I05", "Schema Validation", "验证结构化输出并报告可定位的错误。", "procedural"),
  a("I04", "Context Engineering", "选择并组织指令、历史、知识、记忆与工具结果。", "procedural"),
  a("T11", "Tool Interface", "定义 Agent 可发现和调用的工具契约。", "representational"),
  a("T12", "Function Calling", "使用模型的函数调用协议表达工具请求。", "procedural"),
  a("T03", "Tool Selection", "根据任务和工具描述选择合适工具。", "meta"),
  a("T14", "Tool Arguments", "生成并校验符合接口的工具参数。", "representational"),
  a("T15", "Tool Execution", "调用外部能力并管理一次执行。", "procedural"),
  a("T06", "Tool Result", "解析、归一化并注入工具执行结果。", "representational"),
  a("T07", "Tool Failure", "识别参数、权限、超时和执行失败。", "conceptual"),
  a("T08", "Tool Retry", "对可恢复工具失败实施有界重试。", "procedural"),
  a("T09", "Tool Permission", "限制工具可访问的资源和动作。", "procedural"),
  a("T10", "Tool Approval", "对高风险工具动作请求人工确认。", "procedural"),
  a("K01", "Document Parsing", "从文档载体提取结构化内容。", "procedural"),
  a("K12", "Chunking", "把内容切分为语义完整、可检索单元。", "procedural"),
  a("K13", "Embedding", "将内容编码为可比较的向量表示。", "representational"),
  a("K14", "Retrieval", "从知识源召回与查询相关的候选内容。", "procedural"),
  a("K15", "Reranking", "对召回候选按任务相关性重新排序。", "procedural"),
  a("K16", "Citation", "把生成结论追溯到明确来源。", "procedural"),
  a("K04", "Working State", "维护一次任务或会话中的工作状态。", "representational"),
  a("K05", "Long-term Memory", "跨会话读取、写入、更新和遗忘记忆。", "procedural"),
  a("RT01", "Agent Loop", "构造 Observe–Think–Act 的自主执行循环。", "procedural"),
  a("RT02", "Task State Machine", "用状态和转换表达 Agent 任务生命周期。", "representational"),
  a("RT03", "Runtime Limit", "为步骤、次数、时间和资源设置运行边界。", "procedural"),
  a("RT14", "Failure Recovery", "从可恢复运行失败中安全继续或降级。", "procedural"),
  a("RT15", "Checkpoint", "保存可用于恢复执行的完整中间状态。", "procedural"),
  a("RT06", "Audit Trail", "记录可追溯的输入、决策、动作与结果。", "representational"),
  a("W13", "Orchestrator", "拆分任务并协调多个执行单元。", "procedural"),
  a("W04", "Worker", "接收明确子任务并返回受约束结果。", "procedural"),
  a("WF03", "Orchestrator-Worker Workflow", "把协调者与 Worker 组织成可执行工作流。", "procedural"),
  a("WF05", "Agentic Workflow", "组合确定性步骤、Agent 决策、评估与审批。", "procedural"),
  a("MA02", "Supervisor", "由中央 Agent 分配任务并整合专业 Agent 结果。", "procedural"),
  a("MA12", "Multi-agent Delegation", "在多个 Agent 之间分配职责和上下文。", "procedural"),
  a("MA03", "Tool", "理解可调用、具有输入输出契约的原子外部能力。", "conceptual"),
  a("MA04", "Skill", "理解封装知识、指令和工作流的可复用能力。", "conceptual"),
  a("MA15", "Plugin", "理解打包技能、工具与集成的扩展单元。", "conceptual"),
  a("MA06", "Model Context Protocol", "理解 MCP 的客户端、服务端与能力发现边界。", "conceptual"),
  a("MA07", "Agent-to-Agent Protocol", "理解远程 Agent 之间的能力发现与任务协作。", "conceptual"),
  a("E12", "Benchmark Task", "设计可重复执行、结果可比较的基准任务。", "procedural"),
  a("E13", "Outcome Evaluation", "依据验收标准评测最终结果。", "procedural"),
  a("E14", "Trajectory Evaluation", "评测计划、工具调用和中间步骤。", "procedural"),
  a("E05", "Regression Test", "用固定用例识别 Agent 能力与行为退化。", "procedural"),
  a("E06", "Observability", "用日志、指标和 Trace 观察 Agent 系统。", "conceptual"),
  a("E07", "Runtime Debugging", "依据运行信号定位 Agent 执行故障。", "procedural"),
  a("S01", "Guardrail", "在输入、输出和动作边界实施安全规则。", "procedural"),
  a("S02", "Sandbox", "在隔离环境限制代码与工具副作用。", "procedural"),
  a("S03", "Least Privilege", "仅授予完成任务所需的最小权限。", "conceptual"),
  a("S14", "API Service", "通过稳定接口提供 Agent 服务。", "procedural"),
  a("S15", "Database Persistence", "将 Agent 状态与业务数据可靠持久化。", "procedural"),
  a("S06", "Task Queue", "用队列缓冲、排序和分发异步任务。", "procedural"),
  a("S07", "Worker", "从任务队列消费并执行 Agent 工作。", "procedural"),
  a("S08", "Deployment", "把 Agent 服务发布到可运行环境。", "procedural"),
  a("BR01", "Async Tool Execution", "在异步 Runtime 中可靠执行外部工具并处理结果、超时与生命周期。", "procedural", undefined, ["async", "tool", "runtime"]),
];
