import type { EdgeSeed } from "./demoKnowledgeEdgeFactory.fixture";

/** Manually reviewed canonical relations for the Python Engineering demo Domain. */
export const pythonEngineeringEdgeSeeds: EdgeSeed[] = [
  ["PY01", "PY02", "prerequisite", "hard", "Python object and reference behavior depends on the runtime's execution and memory model."],
  ["PY02", "PY03", "prerequisite", "soft", "Built-in values are manipulated through Python's object and reference semantics."],
  ["PY03", "PY04", "prerequisite", "hard", "Expressions operate on values provided by Python's built-in types."],
  ["PY04", "PY05", "prerequisite", "hard", "Control-flow conditions and loop bodies are composed from expressions."],
  ["PY05", "PY06", "prerequisite", "hard", "Functions encapsulate reusable behavior expressed with control flow."],
  ["PY06", "PY07", "prerequisite", "hard", "Function name resolution and closures require understanding Python scope."],
  ["PY06", "PY08", "enables", 0.8, "Functions provide reusable units that modules organize and export."],
  ["PY09", "PY46", "enables", 0.55, "Exception handling lets an HTTP client represent transport and protocol failures safely."],
  ["PY08", "PY34", "enables", 0.82, "Modules are the primary code units arranged by a Python project structure."],
  ["PY18", "PY45", "enables", 0.62, "JSON is a common representation for HTTP request and response bodies."],
  ["PY45", "PY46", "prerequisite", "hard", "Correct HTTP client use requires understanding requests, responses, methods, and status codes."],
  ["PY99", "PY55", "related", 0.8, "The GIL directly affects how Python threads execute bytecode concurrently."],
  ["PY54", "PY55", "related", 0.68, "Processes are commonly contrasted with GIL-constrained threads for CPU parallelism."],
  ["PY56", "PY57", "prerequisite", "hard", "async/await expresses work scheduled and resumed by an event loop."],
  ["PY57", "PY58", "prerequisite", "hard", "Async tasks wrap and schedule coroutine work expressed with async/await."],
  ["PY58", "PY100", "enables", 0.84, "Async tasks can be bounded by timeout wrappers and deadlines."],
  ["PY58", "PY63", "enables", 0.8, "Task handles provide the identity and lifecycle needed to request cancellation."],
  ["PY100", "PY62", "enables", 0.64, "Timeout failures are a common trigger for bounded retry and backoff."],
  ["PY64", "PY67", "enables", 0.85, "SQL knowledge grounds queries and transactions expressed through SQLAlchemy."],
  ["PY71", "PY72", "enables", 0.72, "Redis provides a concrete persistence mechanism for cache and short-lived state."],
  ["PY76", "PY78", "enables", 0.68, "State machines define lifecycle transitions for background work."],
  ["PY78", "PY101", "enables", 0.8, "Background work can be buffered and distributed through a task queue."],
  ["PY101", "PY80", "prerequisite", "hard", "A queue worker requires a task queue from which it consumes messages."],
  ["PY102", "PY83", "enables", 0.86, "Plugin objects provide the capabilities registered for later discovery and selection."],
  ["PY82", "PY102", "enables", 0.8, "Dynamic import loads plugin implementations at runtime."],
  ["PY37", "PY85", "enables", 0.8, "pytest supplies the runner and assertion model used to implement unit tests."],
  ["PY85", "PY86", "prerequisite", "soft", "Unit testing concepts ground the broader boundaries exercised by integration tests."],
  ["PY89", "PY90", "related", 0.66, "Structured logs and metrics are complementary signals for service observability."],
  ["PY90", "PY91", "related", 0.72, "Metrics and traces provide aggregate and request-level views of service behavior."],
  ["PY49", "PY50", "enables", 0.9, "FastAPI uses Pydantic models for typed request parsing and response validation."],
  ["PY94", "PY50", "enables", 0.88, "FastAPI runs as an application built on the ASGI server interface."],
  ["PY50", "PY98", "enables", 0.72, "A FastAPI application is a concrete Python service prepared for deployment."],
  ["PY95", "PY98", "enables", 0.8, "Docker packages a Python service into a reproducible deployment artifact."],
  ["PY51", "PY97", "related", 0.62, "Authentication relies on safely stored credentials, tokens, and signing secrets."],

  ["PY06", "PY27", "enables", 0.86, "Function parameters and return values are the primary interfaces described by type hints."],
  ["PY07", "PY08", "prerequisite", "soft", "Module organization depends on understanding module-level and imported name scope."],
  ["PY34", "PY37", "enables", 0.82, "Project structure gives pytest stable locations for tests, fixtures, and configuration."],
  ["PY09", "PY85", "enables", 0.78, "Unit tests need explicit exception expectations to verify failure behavior."],
  ["PY27", "PY85", "enables", 0.68, "Type hints make function contracts clearer when designing focused unit tests."],
  ["PY19", "PY18", "enables", 0.88, "File and path operations provide the storage boundary for reading and writing JSON documents."],
  ["PY03", "PY18", "enables", 0.7, "JSON values map directly onto a constrained set of Python built-in types."],
  ["PY18", "PY49", "enables", 0.86, "Pydantic parses and validates structured JSON-shaped data."],
  ["PY27", "PY49", "enables", 0.92, "Pydantic derives field and model contracts from Python type annotations."],
  ["PY45", "PY50", "prerequisite", "soft", "Building an API service requires the semantics of HTTP requests, responses, and status codes."],
  ["PY50", "PY51", "enables", 0.8, "A FastAPI service provides request boundaries where authentication is enforced."],
  ["PY97", "PY51", "enables", 0.9, "Secure authentication requires protected keys, tokens, and credentials."],
  ["PY46", "PY51", "enables", 0.78, "Authenticated external API calls require the HTTP client to attach and refresh credentials."],
  ["PY01", "PY99", "prerequisite", "soft", "Thread behavior is interpreted relative to the Python runtime and its shared process state."],
  ["PY01", "PY54", "prerequisite", "soft", "Process isolation and startup behavior depend on the Python runtime environment."],
  ["PY01", "PY56", "prerequisite", "soft", "The event loop is an alternative scheduling model within the Python runtime."],
  ["PY57", "PY46", "related", 0.82, "async/await is the control-flow model used by non-blocking HTTP client requests."],
  ["PY46", "PY62", "related", 0.76, "HTTP clients commonly apply retry and backoff to transient transport and server failures."],
  ["PY100", "PY46", "related", 0.82, "Timeouts bound HTTP client operations that may otherwise wait indefinitely."],
  ["PY09", "PY62", "prerequisite", "soft", "Retry policy depends on classifying exceptions as transient or terminal."],
  ["PY56", "PY94", "related", 0.86, "ASGI concurrency is implemented on an event-loop scheduling model."],
  ["PY58", "PY78", "enables", 0.84, "Async tasks provide an in-process mechanism for running background work."],
  ["PY62", "PY78", "enables", 0.75, "Background tasks need bounded retry behavior when temporary failures occur."],
  ["PY67", "PY72", "enables", 0.88, "SQLAlchemy provides durable relational persistence and transaction boundaries."],
  ["PY72", "PY50", "related", 0.7, "API services commonly persist request-driven application state."],
  ["PY08", "PY82", "prerequisite", "hard", "Dynamic import requires understanding Python module names and loading semantics."],
  ["PY34", "PY102", "enables", 0.7, "A project structure defines plugin packages, entry points, and loading boundaries."],
  ["PY09", "PY89", "enables", 0.88, "Structured exception details are essential fields in actionable service logs."],
  ["PY50", "PY89", "enables", 0.82, "A FastAPI service supplies request context for structured application logging."],
  ["PY89", "PY91", "enables", 0.82, "Structured correlation identifiers connect log events to trace spans."],
  ["PY91", "PY86", "enables", 0.78, "Traces help verify and diagnose interactions exercised by integration tests."],
  ["PY50", "PY95", "enables", 0.78, "A web service is packaged with its runtime and dependencies in a Docker image."],
  ["PY19", "PY34", "enables", 0.66, "Reliable path handling supports portable source, configuration, and test layouts."]
];
