import { readFileSync } from 'node:fs';
import { renderToStaticMarkup } from 'react-dom/server';
import { describe, expect, it } from 'vitest';
import { ConversationWorkbenchShell } from '@/shared/components/ConversationWorkbenchShell';
const read=(file:string)=>readFileSync(file,'utf8');
describe('Unified conversation workbench presentation boundary',()=>{
 it('assembles one header, independently disclosed context and conversation column',()=>{const html=renderToStaticMarkup(<ConversationWorkbenchShell mode="实践" title="任务" description="明确提交" action={<button>返回</button>} context={<p>任务上下文</p>}><p>时间线与输入</p></ConversationWorkbenchShell>);for(const part of ['workbench-header','workbench-context','workbench-conversation','任务上下文','时间线与输入'])expect(html).toContain(part);expect(read('src/shared/components/ConversationWorkbenchShell.tsx')).not.toMatch(/applicationServices|features\/|apiRequest|localStorage/);});
 it('both product surfaces use the same shell with viewport-scoped scrolling',()=>{expect(read('src/features/course/pages/AssignmentExperiencePage.tsx')).toContain('<ConversationWorkbenchShell');expect(read('src/features/evidence/EvidenceWorkspace.tsx')).toContain('<ConversationWorkbenchShell');const css=read('src/features/assistant/conversation/conversationWorkspace.css');expect(css).not.toContain('62vh');expect(css).not.toContain('58vh');expect(css).toContain('.conversation-composer { flex:none;');expect(css).toContain('.assistant-conversation.compact .conversation-timeline { max-height:220px;');expect(read('src/shared/components/conversationWorkbench.css')).toContain('min-height:0; overflow:hidden;');expect(read('src/features/evidence/evidence.css').split('\n')[1]).toContain('overflow:hidden');});
 it('scopes new-message autoscroll to timeline instead of scrolling its ancestors',()=>{const source=read('src/features/assistant/conversation/ConversationWorkspace.tsx');expect(source).toContain('timeline.current?.scrollTo');expect(source).not.toContain('scrollIntoView');});
 it('keeps formal practice submission and capability confirmation behind explicit existing authorities',()=>{const practice=read('src/features/course/pages/AssignmentExperiencePage.tsx'),capability=read('src/features/evidence/CapabilityConversation.tsx');expect(practice).toContain('composerActions={!submitted');expect(practice).toContain('submitAssignment(courseId, stableAssignmentId, response,submissionKey.current,actionRunId,true)');expect(capability).toContain("await evidenceRequest({action,runId,proposalIds:batch.map(proposal=>proposal.id)})");expect(capability).not.toMatch(/persistRoute|action:'adopt'|action:'restore'/);expect(capability).toContain('?view=project&routeImpact=1');});
 it('starts source picker, history and technical metadata folded and offers no failed refresh',()=>{const source=read('src/features/evidence/CapabilityConversation.tsx');expect(source).not.toContain('open={!runId}');expect(source).toContain('<summary>本次资料 · 已选择');expect(source).toContain('<summary>历史分析');expect(source).toContain('<summary>技术详情</summary>');const failed=source.split("run.run.status==='failed'?<>")[1].split("run.run.status==='running'")[0];expect(failed).toContain('本次分析未完成');expect(failed.match(/>重新分析</g)).toHaveLength(1);expect(failed).not.toContain('refresh()');expect(source).not.toContain('刷新本次结果');expect(source).not.toContain('分析 {run.run.id}');expect(source).not.toContain('记录 ${message.structuredContent.referenceId}');expect(source).toContain("if(!(error instanceof ApiRequestError");});
 it('keeps Overview a native absolute disclosure independent of graph and camera',()=>{const source=read('src/features/course/capability/ProjectCapabilityView.tsx');expect(source).toContain('<details className="project-overview');expect(source).not.toMatch(/overviewOpen|setOverview|onToggle/);const css=read('src/features/course/capability/projectCapability.css');expect(css).toContain('top:var(--project-top-control-band)');expect(css).not.toContain('top:148px; left:50%');});
 it('disables nonessential motion without removing controls',()=>{expect(read('src/shared/components/conversationWorkbench.css')).toContain('@media(prefers-reduced-motion:reduce)');expect(read('src/features/assistant/conversation/ConversationWorkspace.tsx')).toContain('y: reduced ? 0 : 4');expect(read('src/shared/components/ConversationWorkbenchShell.tsx')).toContain('media.addEventListener');});
});
