import {beforeEach,expect,it,vi} from 'vitest';
import type {VercelRequest,VercelResponse} from '@vercel/node';
const mocks=vi.hoisted(()=>({user:vi.fn(),server:vi.fn(),diagnose:vi.fn(),embed:vi.fn(),rpc:vi.fn()}));
vi.mock('../_lib/supabase.js',()=>({createUserSupabase:mocks.user,createServerSupabase:mocks.server}));
vi.mock('../_lib/env.js',()=>({readLlmEnvironment:()=>({llmModel:'acceptance-test'}),readEmbeddingEnvironment:()=>({embeddingModel:'test-embedding',embeddingProvider:'test',embeddingDimensions:2})}));
vi.mock('../_lib/llm.js',()=>({OpenAICompatibleJsonGenerationClient:class{}}));
vi.mock('../_lib/embedding.js',()=>({createEmbeddingService:()=>({embed:mocks.embed})}));
vi.mock('../../src/features/evidence/diagnosis.js',async importOriginal=>({...await importOriginal<object>(),diagnoseEvidence:mocks.diagnose}));
import handler from './evidence';
type Row=Record<string,any>;
const source='10000000-0000-4000-8000-000000000001';
let rows:Record<string,Row[]>;let writes:string[];let next=10;
function client(){return {from(table:string){let selected=[...(rows[table]??[])];let patch:Row|undefined;function result(){if(patch)for(const row of selected)Object.assign(row,patch);return {data:selected,error:null};}const q={select(){return q;},eq(key:string,value:unknown){selected=selected.filter(row=>row[key]===value);return q;},in(key:string,values:unknown[]){selected=selected.filter(row=>values.includes(row[key]));return q;},is(key:string,value:unknown){selected=selected.filter(row=>row[key]===value);return q;},insert(value:Row|Row[]){writes.push(table);rows[table]??=[];const values=(Array.isArray(value)?value:[value]).map(row=>({id:`10000000-0000-4000-8000-${String(next++).padStart(12,'0')}`,status:'running',...row}));rows[table].push(...values);selected=values;return q;},update(value:Row){writes.push(table);patch=value;return q;},single(){result();return Promise.resolve({data:selected[0]??null,error:null});},then(resolve:(value:unknown)=>unknown){return Promise.resolve(result()).then(resolve);}};return q;},rpc:mocks.rpc};}
async function request(body:unknown){let status=0,payload:Row={};const response={setHeader(){},status(code:number){status=code;return response;},json(data:Row){payload=data;}};await handler({method:'POST',body,headers:{}} as VercelRequest,response as unknown as VercelResponse);return {status,body:payload};}
beforeEach(()=>{vi.resetAllMocks();writes=[];rows={user_evidence_sources:[{id:source,user_id:'owned',parse_status:'ready',archived_at:null,parsed_lines:[{line:1,text:'本人工作原始输入'}]}],capability_diagnosis_runs:[{id:'old-run',status:'completed',source_ids:[source],user_id:'owned',diagnostics:{immutable:true}}]};mocks.user.mockResolvedValue({user:{id:'owned'},client:client()});mocks.server.mockReturnValue(client());mocks.rpc.mockResolvedValue({data:0,error:null});mocks.embed.mockResolvedValue([1,0]);mocks.diagnose.mockResolvedValue({units:[],matches:[],metadata:{},artifacts:[],retrievalCount:0,llmCalls:1});});
it('each explicit analysis creates a distinct Run and does not overwrite the historical Run or capability/Route',async()=>{const original=JSON.stringify(rows.capability_diagnosis_runs[0]);const first=await request({action:'diagnose',sourceIds:[source]});const second=await request({action:'diagnose',sourceIds:[source]});expect(first.status).toBe(201);expect(second.status).toBe(201);expect(first.body.runId).not.toBe(second.body.runId);expect(JSON.stringify(rows.capability_diagnosis_runs[0])).toBe(original);expect(rows.capability_diagnosis_runs).toHaveLength(3);expect(writes.every(table=>['capability_diagnosis_runs','evidence_units','capability_state_proposals'].includes(table))).toBe(true);});
it.each(['diagnosis timeout','embedding timeout'])('a %s keeps an auditable failed Run with no capability/Route update and retry creates a new Run',async failure=>{const original=JSON.stringify(rows.capability_diagnosis_runs[0]);if(failure==='embedding timeout'){mocks.embed.mockRejectedValueOnce(new Error(failure));mocks.diagnose.mockImplementationOnce(async(_sources:unknown,_model:unknown,retrieve:(text:string)=>Promise<unknown>)=>{await retrieve('actual capability');});}else mocks.diagnose.mockRejectedValueOnce(new Error(failure));const result=await request({action:'diagnose',sourceIds:[source]});expect(result.status).toBe(503);expect(result.body.error).toMatchObject({code:'diagnosis_failed',details:{runId:rows.capability_diagnosis_runs[1].id}});expect(rows.capability_diagnosis_runs[1].status).toBe('failed');expect(JSON.stringify(rows.capability_diagnosis_runs[0])).toBe(original);expect(writes).toEqual(['capability_diagnosis_runs','capability_diagnosis_runs']);const retry=await request({action:'diagnose',sourceIds:[source]});expect(retry.status).toBe(201);expect(retry.body.runId).not.toBe(result.body.error.details.runId);expect(rows.capability_diagnosis_runs[1].status).toBe('failed');});
it('foreign or unready source selection and unavailable embedding index do not start a half analysis',async()=>{expect((await request({action:'diagnose',sourceIds:['10000000-0000-4000-8000-000000000999']})).status).toBe(404);mocks.rpc.mockResolvedValueOnce({data:1,error:null});expect((await request({action:'diagnose',sourceIds:[source]})).status).toBe(503);expect(rows.capability_diagnosis_runs).toHaveLength(1);expect(writes).toEqual([]);});
