import { mechanismFeedback } from "@/shared/learning/microMechanisms";
import { NativeInteraction, initialAnswer } from "./NativeInteraction";
import { ArrowLeft,ArrowRight,Check,RotateCcw } from "lucide-react";
import { lazy,Suspense,useCallback,useEffect,useMemo,useState } from "react";
import { useLocation,useNavigate,useParams,useSearchParams } from "react-router-dom";
import { GlobalNav } from "@/app/components/GlobalNav";
import { applicationServices,refreshLearnerState } from "@/app/services/applicationServices";
import { EduFlowAssistant } from "@/features/assistant/components/EduFlowAssistant";
import type { MockSession } from "@/features/auth/types";
import { firstMicroReviewStep,resolveMicroResumeStep,isMicroReviewSubmissionCorrect,nextMicroReviewStep,resolveMicroLearningReturnTarget,type H5PContentDescriptor,type H5PResult,type MicroInteraction,type MicroLearningAnswer,type MicroLearningRepository,type MicroReviewCursor,type MicroStep } from "./microLearning";
import type { NavigationDecision } from "@/shared/learning/navigation";

const H5PPlayer=lazy(()=>import("./H5PInteraction").then((module)=>({default:module.H5PInteraction})));
const hasAnswer=(answer:MicroLearningAnswer)=>Array.isArray(answer)?answer.length>0&&answer.every((item)=>typeof item!=="string"||Boolean(item.trim())):typeof answer==="object"?answer.executed>0:Boolean(answer);

export function MicroLearningExperience({session,onLogout,repository}:{session:MockSession|null;onLogout():void;repository:MicroLearningRepository}) {
  const navigate=useNavigate(),location=useLocation(),{knowledgeId=""}=useParams(),[searchParams]=useSearchParams(); const courseId=searchParams.get("courseId")??undefined;
  const [revision,setRevision]=useState(0),[answer,setAnswer]=useState<MicroLearningAnswer>(""),[touched,setTouched]=useState(false),[grading,setGrading]=useState<"success"|"retry"|"error"|null>(null),[whyOpen,setWhyOpen]=useState(false),[busy,setBusy]=useState(false),[pinned,setPinned]=useState<{unitId:string;stepId:string}|null>(null),[reviewCursor,setReviewCursor]=useState<MicroReviewCursor|null>(null),[navigationDecision,setNavigationDecision]=useState<NavigationDecision|null>(null),[navigationError,setNavigationError]=useState(false),[startError,setStartError]=useState(false);
  useEffect(()=>repository.subscribe(()=>setRevision((value)=>value+1)),[repository]);
  const path=useMemo(()=>repository.getPath(knowledgeId,{courseId,mode:"learn"}),[courseId,knowledgeId,repository,revision]); const progress=path?repository.getPathProgress(path.id):undefined;
  useEffect(()=>{if(path&&progress?.status!=="completed"&&progress?.status!=="in_progress"){setStartError(false);void repository.start(path.id,courseId).catch(()=>setStartError(true));}},[courseId,path,progress?.status,repository]);
  useEffect(()=>{if(session&&courseId&&progress?.status==="completed"&&!pinned){setNavigationError(false);void applicationServices.learnerStateService.getNavigation(courseId).then(setNavigationDecision).catch(()=>setNavigationError(true));}},[courseId,pinned,progress?.status,session]);
  useEffect(()=>{setReviewCursor(null);setPinned(null);},[path?.id]);
  const unit=path?.units.find((item)=>item.id===(reviewCursor?.unitId??pinned?.unitId??progress?.currentUnitId))??path?.units[0]; const step=unit?(reviewCursor||pinned?unit.steps.find((item)=>item.id===(reviewCursor?.stepId??pinned?.stepId))??unit.steps[0]:resolveMicroResumeStep(unit,repository.getUnitProgress(unit.id),progress?.currentStepId)):undefined;
  const returnTarget=resolveMicroLearningReturnTarget(location.state,courseId); const context=session?{workspace:"learning" as const,experienceMode:"learn" as const,userRole:session.role,capabilities:session.capabilities,courseId,knowledgeId}:undefined;
  useEffect(()=>{setAnswer(initialAnswer(step?.interaction));setTouched(false);setGrading(null);setWhyOpen(false);},[step?.id]);
  const completeCurrent=useCallback(async(submission?:MicroLearningAnswer|{kind:"h5p-result";contentRef:string;eventId:string;result:H5PResult})=>{if(!path||!unit||!step||busy)return;if(reviewCursor){setGrading(isMicroReviewSubmissionCorrect(step.interaction,submission??(step.interaction?answer:undefined))?"success":"retry");return;}setBusy(true);setPinned({unitId:unit.id,stepId:step.id});try{const result=await repository.completeStep(path.id, unit.id, step.id,submission??(step.interaction?answer:undefined),courseId);setGrading(result.correct?"success":"retry");if(result.correct&&session)await refreshLearnerState(session.userId);else if(!result.correct)setPinned(null);}catch{setGrading("error");setPinned(null);}finally{setBusy(false);}},[answer,busy,courseId,path,repository,reviewCursor,session,step,unit]);
  if(!path)return <main className="micro-learning-page"><GlobalNav active="learning" session={session} onLogout={onLogout}/><Unsupported title="该知识暂不支持快速学习" body="当前还没有已发布的 MicroLearningPath。你仍然可以返回来源，或继续查看关联课件。" onBack={()=>navigate(returnTarget)}/></main>;
  if(!unit||!step)return <main className="micro-learning-page"><GlobalNav active="learning" session={session} onLogout={onLogout}/><Unsupported title="该快速学习内容尚未完整发布" body="发布内容缺少必要 Unit 或 Step。" onBack={()=>navigate(returnTarget)}/></main>;
  const total=path.units.reduce((sum,item)=>sum+item.steps.length,0),currentIndex=path.units.filter((item)=>item.position<unit.position).reduce((sum,item)=>sum+item.steps.length,0)+unit.steps.findIndex((item)=>item.id===step.id)+1,reviewingCompletedPath=Boolean(reviewCursor),showCompleted=progress?.status==="completed"&&!pinned&&!reviewingCompletedPath,interaction=step.interaction;
  const nextActionHref=navigationDecision?.nextAction.resourceKind==="assignment"&&navigationDecision.nextAction.resourceId?`/courses/${encodeURIComponent(courseId!)}/assignments/${encodeURIComponent(navigationDecision.nextAction.resourceId)}`:navigationDecision?.nextAction.resourceKind==="material"&&navigationDecision.nextAction.resourceId?`/courses/${encodeURIComponent(courseId!)}/materials/${encodeURIComponent(navigationDecision.nextAction.resourceId)}`:returnTarget;
  const concreteFeedback=interaction&&(interaction.type==="flow-execution"||interaction.type==="simulation"||interaction.type==="data-transform")?mechanismFeedback(interaction,answer).message:interaction?.type==="categorize"&&Array.isArray(answer)?interaction.items.flatMap((item,index)=>answer[index]!==interaction.correctCategories[index]?[`「${item.label}」应归入「${interaction.correctCategories[index]}」。`]:[]).join(" ")+" "+(step.retryFeedback??""):interaction?.type==="ordering"&&Array.isArray(answer)?`第 ${interaction.correctOrder.findIndex((item,index)=>item!==answer[index])+1} 个位置不符合刚才的过程。${step.retryFeedback??"请检查因果顺序。"}`:undefined;
  const feedback=grading==="success"?(step.successFeedback??(reviewingCompletedPath?"判断正确；复习结果不会改写原进度。":session?"判断正确，进度已保存。":"判断正确；本次匿名体验不会保存进度。")):grading==="retry"?((concreteFeedback||step.retryFeedback)??"答案尚未满足完成条件，请重试。"):grading==="error"?(session?"保存失败，进度没有被推进。请重试。":"检查失败，请重试；匿名体验没有产生持久记录。"):null;
  return <main className="micro-learning-page"><GlobalNav active="learning" session={session} onLogout={onLogout}/><header className="micro-learning-header"><button onClick={()=>navigate(returnTarget)}><ArrowLeft size={16}/>返回</button><span><small>MICRO LEARNING · {path.estimatedMinutes} 分钟</small><strong>{path.title}</strong></span><i>{showCompleted?total:currentIndex} / {total}</i></header>
    <section className="micro-learning-stage">{startError?<div className="micro-feedback retry" role="alert">学习尚未成功启动；当前 Step 不会被记录。<button type="button" onClick={()=>{setStartError(false);void repository.start(path.id,courseId).catch(()=>setStartError(true));}}>重试启动</button></div>:null}<div className="micro-progress" aria-label={`学习进度 ${showCompleted?total:currentIndex-1}/${total}`}><i style={{width:`${((showCompleted?total:currentIndex-1)/Math.max(total,1))*100}%`}}/></div>
      {showCompleted?<article className="micro-card micro-complete"><Check size={36}/><span className="atlas-kicker">PATH COMPLETED</span><h1>这条微学习路径已完成</h1><p>{session?"完成已持久化为学习证据；主动复习不会清空进度、重复完成证据或降低学习状态。":"你已完成一次匿名本地体验；答案与进度不会写入账户或 learner state。"}</p>{navigationDecision?<section className="micro-next-action"><small>NEXT ACTION · {navigationDecision.policyVersion}</small><strong>{navigationDecision.nextAction.kind==="practice"?"用实训证明掌握":"继续学习路线"}</strong><span>{navigationDecision.nextAction.reason}</span></section>:navigationError?<div className="micro-feedback retry" role="alert">下一步暂时无法加载；学习进度已保存，你可以重试或返回课程。</div>:null}<div><span className="atlas-pill"><RotateCcw size={15}/>{session?"已完成 · 可复习":"匿名体验 · 未保存"}</span><button className="atlas-secondary" onClick={()=>setReviewCursor(firstMicroReviewStep(path))}><RotateCcw size={15}/>重新复习</button>{navigationError&&courseId?<button className="atlas-secondary" onClick={()=>{setNavigationError(false);void applicationServices.learnerStateService.getNavigation(courseId).then(setNavigationDecision).catch(()=>setNavigationError(true));}}>重试下一步</button>:null}<button className="atlas-primary" onClick={()=>navigate(navigationDecision?nextActionHref:returnTarget)}>{navigationDecision?"前往下一步":"返回来源"}<ArrowRight size={15}/></button></div></article>:
      <article className={`micro-card micro-step-${grading??"active"}`}><span className="atlas-kicker">UNIT {unit.position+1} · {step.kind.toUpperCase()}</span><h1>{step.title}</h1><p>{step.body}</p>
        {interaction?.type==="h5p"?<H5PStep repository={repository} pathId={path.id} unitId={unit.id} stepId={step.id} interaction={interaction} onResult={(eventId,result)=>void completeCurrent({kind:"h5p-result",contentRef:interaction.contentRef,eventId,result})}/>:interaction?<NativeInteraction key={step.id} step={step} answer={answer} completed={grading==="success"} onAnswer={(value)=>{setAnswer(value);setTouched(true);setGrading(null);}}/>:null}
        {feedback?<div className={`micro-feedback ${grading==="success"?"success":"retry"}`} role="status">{feedback}</div>:null}
        {whyOpen?<div className="micro-inline-explanation"><strong>提示</strong><p>{grading==="success"?(step.successFeedback??"已完成这一步。"):(step.retryFeedback??"先识别当前步骤要求验证的边界、因果或执行顺序。")}</p></div>:null}
        <footer><button className="atlas-secondary" onClick={()=>setWhyOpen((value)=>!value)}>{whyOpen?"收起提示":"为什么？"}</button>{reviewingCompletedPath?<span className="atlas-pill">复习模式 · 不改写原进度</span>:<span/>}{grading==="success"?<button className="atlas-primary" onClick={()=>{if(reviewCursor){setReviewCursor(nextMicroReviewStep(path,reviewCursor));}else setPinned(null);setGrading(null);}}>继续<ArrowRight size={15}/></button>:interaction?.type==="h5p"?null:interaction?<button className="atlas-primary" disabled={busy||!hasAnswer(answer)||((interaction.type==="parameter-lab"||interaction.type==="matrix-tensor")&&!touched)} onClick={()=>void completeCurrent()}>{busy?"检查中…":"检查答案"}</button>:<button className="atlas-primary" disabled={busy} onClick={()=>void completeCurrent()}>{busy?"保存中…":"继续"}<ArrowRight size={15}/></button>}</footer>
      </article>}
    </section><EduFlowAssistant context={context?{...context,microPathId:path.id,microUnitId:unit.id,microStepId:step.id}:undefined} locked={!session} contextLabel={path.title}/></main>;
}

function Unsupported({title,body,onBack}:{title:string;body:string;onBack():void}) { return <section className="micro-unsupported"><button className="micro-unsupported-back" onClick={onBack}><ArrowLeft size={16}/>返回</button><div><span className="atlas-kicker">MICRO LEARNING</span><h1>{title}</h1><p>{body}</p><button className="atlas-primary" onClick={onBack}>返回来源<ArrowRight size={15}/></button></div></section>; }

function H5PStep({repository,pathId,unitId,stepId,interaction,onResult}:{repository:MicroLearningRepository;pathId:string;unitId:string;stepId:string;interaction:Extract<MicroInteraction,{type:"h5p"}>;onResult(eventId:string,result:H5PResult):void}) {
  const [descriptor,setDescriptor]=useState<H5PContentDescriptor|null>(null),[error,setError]=useState(false),[attempt,setAttempt]=useState(0);
  useEffect(()=>{let live=true;setDescriptor(null);setError(false);void repository.resolveH5PContent(pathId,unitId,stepId,interaction.contentRef).then((value)=>{if(live)setDescriptor(value);}).catch(()=>{if(live)setError(true);});return()=>{live=false;};},[attempt,interaction.contentRef,pathId,repository,stepId,unitId]);
  if(error)return <div className="micro-feedback retry" role="alert"><strong>该互动内容暂时无法加载</strong><span>内容引用不可用，当前 Step 不会被跳过。</span><button type="button" onClick={()=>setAttempt((value)=>value+1)}>重试</button></div>;
  if(!descriptor)return <p className="micro-h5p-loading" role="status">正在验证互动内容…</p>;
  return <Suspense fallback={<p className="micro-h5p-loading">正在载入 H5P Runtime…</p>}><H5PPlayer descriptor={descriptor} onResult={onResult}/></Suspense>;
}
