import type { KnowledgeNode } from "../../knowledge/types";
import { legacyPythonNode as legacyPython, pythonNode as p, splitPythonNode as splitPython } from "./demoKnowledgeNodeFactory.fixture";

export const pythonEngineeringNodes: KnowledgeNode[] = [
  p("PY01", "Python Runtime", "理解 Python 程序的运行环境与执行模型。"),
  p("PY02", "Object / Reference", "理解对象、引用及变量绑定。"),
  p("PY03", "Built-in Types", "掌握 Python 内置类型及其基本行为。"),
  p("PY04", "Expressions", "使用表达式组合值、运算和调用。", "language"),
  p("PY05", "Control Flow", "使用条件与循环控制程序执行。", "language"),
  p("PY06", "Function", "定义参数、返回值与可复用函数行为。", "language"),
  p("PY07", "Scope", "理解局部、闭包与模块作用域。"),
  p("PY08", "Module", "用模块组织和复用 Python 代码。", "procedural"),
  p("PY09", "Exception", "使用异常表达和处理失败。", "procedural"),
  p("PY18", "JSON", "在 Python 与外部系统之间交换结构化 JSON 数据。", "representational"),
  p("PY19", "File / Path", "可靠读写文件并操作路径。", "procedural"),
  p("PY27", "Type Hint", "用类型标注描述函数和数据结构接口。", "language"),
  p("PY34", "Project Structure", "组织可维护的包、模块、配置与测试目录。", "procedural"),
  p("PY37", "pytest", "使用 pytest 编写和运行自动化测试。", "procedural"),
  p("PY45", "HTTP", "理解 HTTP 请求、响应与接口交互。"),
  p("PY46", "HTTP Client", "使用 Python HTTP Client 调用外部 API。", "procedural"),
  p("PY49", "Pydantic", "用类型驱动的数据模型完成解析与校验。", "procedural"),
  p("PY50", "FastAPI", "基于类型和 ASGI 构建 Python API 服务。", "procedural"),
  p("PY51", "Authentication", "处理服务和外部 API 的身份认证。", "procedural"),
  legacyPython("PY53", "Thread / Process / GIL", ["PY99", "PY54", "PY55"]),
  splitPython("PY99", "Thread", "使用线程并理解共享内存并发。", "PY53"),
  splitPython("PY54", "Process", "使用进程获得隔离与 CPU 并行。", "PY53"),
  splitPython("PY55", "Global Interpreter Lock", "解释 GIL 对 Python 线程执行的影响。", "PY53"),
  p("PY56", "Event Loop", "理解事件循环如何调度非阻塞工作。"),
  p("PY57", "async / await", "使用 async / await 表达异步控制流。", "language"),
  p("PY58", "Async Task", "创建、调度和等待异步任务。", "procedural"),
  legacyPython("PY61", "Timeout / Cancellation", ["PY100", "PY63"]),
  splitPython("PY100", "Timeout", "为异步操作设置有界执行时间。", "PY61", "procedural"),
  splitPython("PY63", "Cancellation", "请求取消并安全清理异步任务。", "PY61", "procedural"),
  p("PY62", "Retry / Backoff", "使用重试与退避恢复暂时性失败。", "procedural"),
  p("PY64", "SQL", "使用 SQL 查询和修改关系数据。", "language"),
  p("PY67", "SQLAlchemy", "使用 SQLAlchemy 组织数据库访问与事务。", "procedural"),
  p("PY71", "Redis", "使用 Redis 保存缓存与短期状态。", "procedural"),
  p("PY72", "Persistence", "为应用状态设计可靠持久化。", "procedural"),
  p("PY76", "State Machine", "使用状态与转换表达应用生命周期。", "representational"),
  p("PY78", "Background Task", "将非即时工作交给后台执行。", "procedural"),
  legacyPython("PY79", "Task Queue / Worker", ["PY101", "PY80"]),
  splitPython("PY101", "Task Queue", "使用队列缓冲并分发后台任务。", "PY79", "procedural"),
  splitPython("PY80", "Queue Worker", "消费队列消息并可靠执行后台工作。", "PY79", "procedural"),
  legacyPython("PY81", "Plugin / Registry", ["PY102", "PY83"]),
  splitPython("PY102", "Python Plugin", "定义并加载可插拔 Python 能力。", "PY81", "procedural"),
  splitPython("PY83", "Plugin Registry", "注册、发现和选择可插拔能力。", "PY81", "procedural"),
  p("PY82", "Dynamic Import", "在运行时动态加载 Python 模块。", "procedural"),
  p("PY85", "Unit Test", "隔离验证函数和模块的局部行为。", "procedural"),
  p("PY86", "Integration Test", "验证多个组件与外部依赖的协同行为。", "procedural"),
  p("PY89", "Structured Logging", "输出可查询、可关联的结构化日志。", "procedural"),
  p("PY90", "Metrics", "用指标观测服务健康与性能。", "procedural"),
  p("PY91", "Trace / Span", "追踪跨组件执行路径。", "procedural"),
  p("PY94", "ASGI", "理解 Python 异步 Web 服务接口。"),
  p("PY95", "Docker", "使用容器打包一致运行环境。", "procedural"),
  p("PY97", "Secrets", "安全管理认证令牌和运行时秘密。", "procedural"),
  p("PY98", "Deployment", "将 Python 服务部署到可运行环境。", "procedural")
];
