import type { EdgeSeed } from "./demoKnowledgeEdgeFactory.fixture";

/** Ordinary factual relations that cross current demo Domain assignments. */
export const sharedEdgeSeeds: EdgeSeed[] = [
  ["PY18", "I01", "enables", 0.66, "JSON provides a concrete representation for structured model output."],
  ["PY27", "I02", "enables", 0.7, "Python type hints can express field contracts used to define schemas."],
  ["PY49", "I05", "enables", 0.88, "Pydantic performs concrete schema validation for Python data."],
  ["PY06", "T11", "enables", 0.7, "Python functions provide callable behavior behind a tool interface."],
  ["PY27", "T11", "enables", 0.72, "Type hints describe tool input and output contracts."],
  ["PY49", "T14", "enables", 0.82, "Pydantic validates structured tool arguments before execution."],
  ["PY46", "T15", "enables", 0.8, "An HTTP client implements execution for remote API tools."],
  ["PY09", "T07", "enables", 0.76, "Python exceptions represent and classify tool execution failures."],
  ["PY62", "T08", "enables", 0.84, "Retry and backoff implement bounded recovery from transient tool failures."],
  ["PY19", "K01", "enables", 0.78, "File and path handling provides document bytes to a parser."],
  ["PY64", "K04", "enables", 0.62, "SQL can query structured working state stored relationally."],
  ["PY67", "K05", "enables", 0.7, "SQLAlchemy can persist and retrieve long-term memory records."],
  ["PY71", "K04", "enables", 0.75, "Redis supports low-latency task and session working state."],
  ["PY72", "K05", "enables", 0.72, "Persistence design supports durable long-term memory."],
  ["PY76", "RT02", "enables", 0.9, "A Python state machine directly implements task lifecycle states and transitions."],
  ["PY78", "W04", "enables", 0.65, "A background task can execute a bounded worker assignment."],
  ["PY80", "W04", "enables", 0.82, "A queue worker implements a worker that consumes delegated tasks."],
  ["PY102", "MA15", "enables", 0.68, "A Python plugin supplies a concrete packaged extension implementation."],
  ["PY83", "MA15", "enables", 0.7, "A plugin registry provides discovery and selection for installed plugins."],
  ["PY85", "E12", "enables", 0.78, "Unit tests provide repeatable benchmark task cases."],
  ["PY86", "E05", "enables", 0.78, "Integration tests detect regressions across system boundaries."],
  ["PY89", "E06", "enables", 0.86, "Structured logging is a core source of observability events."],
  ["PY90", "E06", "enables", 0.86, "Metrics provide quantitative observability signals."],
  ["PY91", "E07", "enables", 0.82, "Trace spans expose the execution path used in runtime debugging."],
  ["PY50", "S14", "enables", 0.9, "FastAPI implements a typed Python API service."],
  ["PY67", "S15", "enables", 0.85, "SQLAlchemy implements relational database persistence."],
  ["PY101", "S06", "enables", 0.88, "A Python task queue implements queued work distribution."],
  ["PY80", "S07", "enables", 0.88, "A Python queue worker implements the service worker process."],
  ["PY95", "S08", "enables", 0.9, "Docker provides a reproducible artifact for service deployment."],
  ["PY46", "BR01", "enables", 0.76, "An async-capable HTTP client provides non-blocking remote tool I/O."],
  ["PY57", "BR01", "enables", 0.95, "async/await enables non-blocking tool execution."],
  ["PY58", "BR01", "enables", 0.9, "Async tasks track concurrent tool calls and their lifecycle."],
  ["PY100", "BR01", "enables", 0.8, "Timeouts bound asynchronous tool calls."],
  ["PY63", "BR01", "enables", 0.8, "Cancellation stops asynchronous tool work safely."],
  ["T11", "BR01", "prerequisite", "hard", "Async tool execution still requires a defined tool interface."],
  ["T15", "BR01", "prerequisite", "hard", "Async orchestration builds on the semantics of a single tool execution."],
  ["BR01", "RT01", "enables", 0.9, "Async tool execution enables a responsive agent runtime."]
];
