import { ArrowRight, Minus, Pause, Play, Plus, RefreshCcw, Search, Send, Upload, X } from "lucide-react";
import { useMemo, useRef, useState } from "react";
import { useNavigate } from "react-router-dom";
import { GlobalNav } from "@/app/components/GlobalNav";
import { applicationServices, refreshLearnerState } from "@/app/services/applicationServices";
import { EduFlowAssistant } from "@/features/assistant/components/EduFlowAssistant";
import type { MockSession } from "@/features/auth/types";
import type { LearningIntentResolver, LearningIntentResult } from "@/features/explore/learningIntent";
import { KnowledgeAtlasScene, type KnowledgeAtlasSceneHandle } from "@/features/knowledge/components/KnowledgeAtlasScene";
import { useDomainGovernance } from "@/features/knowledge/domain/domainStore";
import { buildGlobalAtlasProjection } from "@/features/knowledge/projections/atlasProjections";
import { globalKnowledgeAccess } from "@/features/knowledge/repository/KnowledgeRepository";

export function ExplorePage({session,onLogout,resolver}:{session:MockSession;onLogout():void;resolver:LearningIntentResolver}){
  const navigate=useNavigate(); const sceneRef=useRef<KnowledgeAtlasSceneHandle>(null); const governance=useDomainGovernance();
  const atlas=useMemo(()=>buildGlobalAtlasProjection(applicationServices.knowledgeRepository.getVisibleGraph(globalKnowledgeAccess),governance,applicationServices.courseRepository.listCourseRuntimes()),[governance]);
  const [selectedId,setSelectedId]=useState<string|null>(null); const [searchMatchId,setSearchMatchId]=useState<string|null>(null); const [query,setQuery]=useState(""); const [goal,setGoal]=useState(""); const [result,setResult]=useState<LearningIntentResult|null>(null); const [resolving,setResolving]=useState(false); const [paused,setPaused]=useState(false); const [starting,setStarting]=useState(false);
  const selected=selectedId?atlas.nodes.find((node)=>node.id===selectedId)??null:null;
  const assistantContext={workspace:"explore" as const,experienceMode:"learn" as const,userRole:session.role,capabilities:session.capabilities,knowledgeId:selectedId??undefined,selectedObject:result?.kind};
  function locate(){const needle=query.trim().toLowerCase();const match=atlas.nodes.find((node)=>node.title.toLowerCase().includes(needle));if(!match)return;setSelectedId(match.id);setSearchMatchId(match.id);}
  async function resolve(){if(!goal.trim()||resolving)return;setResolving(true);try{const next=await resolver.resolve(goal.trim());setResult(next);if(next.knowledge[0]){setSelectedId(next.knowledge[0].id);setSearchMatchId(next.knowledge[0].id);}}finally{setResolving(false);}}
  async function startKnowledge(nodeId:string){if(starting)return;setStarting(true);try{await applicationServices.learnerStateService.startKnowledge(nodeId);await applicationServices.microLearningRepository.hydrate(session.userId);await refreshLearnerState(session.userId);const course=atlas.nodes.find((node)=>node.id===nodeId)?.courseContexts[0];if(course)navigate(`/learn/micro/${encodeURIComponent(nodeId)}?courseId=${encodeURIComponent(course.courseId)}`);else navigate(`/learn/micro/${encodeURIComponent(nodeId)}`);}finally{setStarting(false);}}
  return <main className="explore-page"><GlobalNav active="explore" session={session} onLogout={onLogout}/>
    <KnowledgeAtlasScene ref={sceneRef} className="atlas-star-canvas" variant="global" nodes={atlas.nodes} edges={atlas.edges} selectedId={selectedId} searchMatchId={searchMatchId} autoRotate={!paused&&!selectedId} onNodeClick={(node)=>setSelectedId(node.id)} onBackgroundClick={()=>setSelectedId(null)}/><div className="atlas-home-veil" aria-hidden="true"/>
    <header className="explore-heading"><span className="atlas-kicker">GLOBAL KNOWLEDGE ATLAS</span><h1>探索知识世界</h1><p>先定位已知 Knowledge；不知道从哪里开始时，再告诉 Assistant 你想学什么。</p><label className="explore-search glass-v2"><Search size={16}/><input value={query} onChange={(event)=>setQuery(event.target.value)} onKeyDown={(event)=>event.key==="Enter"&&locate()} placeholder="搜索知识节点……" aria-label="搜索知识节点"/><button onClick={locate}>定位</button></label></header>
    {selected?<aside className="atlas-node-panel glass-v2"><button className="atlas-panel-close" onClick={()=>setSelectedId(null)} aria-label="关闭简介"><X size={17}/></button><div className="atlas-pill"><i style={{background:selected.color}}/>{selected.domainTitle}</div><h2>{selected.title}</h2><p>{selected.description}</p><div className="atlas-metric-grid"><div><strong>1</strong><span>Knowledge</span></div><div><strong>{selected.courseContexts.length||"—"}</strong><span>课程</span></div><div><strong>{atlas.edges.filter((edge)=>edge.source===selected.id||edge.target===selected.id).length}</strong><span>关系</span></div></div><section className="atlas-node-dependencies"><h3>课程上下文</h3><div>{selected.courseContexts.length?selected.courseContexts.map((context)=><button key={context.courseId} onClick={()=>navigate(`/courses/${context.courseId}`)}><ArrowRight size={12}/>{context.courseTitle}</button>):<span>暂无课程引用</span>}</div></section><button className="atlas-primary" disabled={starting} onClick={()=>void startKnowledge(selected.id)}>{starting?"开始中…":"开始学习"}<ArrowRight size={14}/></button></aside>:null}
    <div className="atlas-home-hint glass-v2">拖动旋转 · 滚轮缩放 · 单击 Knowledge 查看详情</div><div className="atlas-home-controls"><button onClick={()=>sceneRef.current?.zoomBy(.9)}><Minus size={17}/></button><button onClick={()=>sceneRef.current?.zoomBy(1.1)}><Plus size={17}/></button><button onClick={()=>setPaused((value)=>!value)}>{paused?<Play size={17}/>:<Pause size={17}/>}</button><button onClick={()=>{setSelectedId(null);setSearchMatchId(null);sceneRef.current?.reset();}}><RefreshCcw size={17}/></button></div>
    <EduFlowAssistant context={assistantContext} contextLabel={selected?.title??"Learning Intent"} className="explore-assistant"><form className="explore-intent-form" onSubmit={(event)=>{event.preventDefault();void resolve();}}><label>我想学什么</label><div><input value={goal} onChange={(event)=>setGoal(event.target.value)} placeholder="例如：构建 Research Agent"/><button disabled={resolving} aria-label="解析学习目标">{resolving?<span className="atlas-spinner"/>:<Send size={15}/>}</button></div></form>{result?<div className="explore-intent-result"><span className="atlas-kicker">{result.kind.toUpperCase()}</span><strong>{result.summary}</strong>{result.knowledge.length?<div className="explore-result-list">{result.knowledge.map((item)=><button key={item.id} onClick={()=>{setSelectedId(item.id);setSearchMatchId(item.id);}}><span>{item.title}</span><small>{item.reason}</small></button>)}</div>:null}{result.courses.map((course)=><button className="assistant-result-cta" key={course.id} onClick={()=>navigate(`/courses/${course.id}`)}>进入 {course.title}<ArrowRight size={13}/></button>)}{result.kind==="choice"?<small>可以进入已有课程，或选择一个 Knowledge 后直接开始学习。</small>:null}{result.kind==="material"?<><p>{result.limitation}</p><button className="assistant-result-cta" onClick={()=>navigate("/courses/create?source=explore",{state:{prompt:result.goal}})}><Upload size={13}/>创建课程</button></>:null}</div>:<p className="assistant-plain-response">它只定位现有 Knowledge 与 Course；系统性学习请使用或创建 Course。</p>}</EduFlowAssistant>
  </main>;
}
