import { useMemo, useState } from "react";
import type { AssignmentCoverage, AssignmentCoverageRole, CourseAssignment } from "@/features/course/types";

const splitLines = (value: string) => value.split("\n").map((line) => line.trim()).filter(Boolean);

export function AssignmentAuthoringEditor({ assignments, coverages, courseId, knowledgeId, onChange }: { assignments: CourseAssignment[]; coverages: AssignmentCoverage[]; courseId: string; knowledgeId: string; onChange: (assignments: CourseAssignment[], coverages: AssignmentCoverage[]) => void }) {
  const linked = useMemo(() => assignments.filter((assignment) => coverages.some((coverage) => coverage.assignmentId === assignment.id && coverage.nodeId === knowledgeId)), [assignments, coverages, knowledgeId]);
  const [title, setTitle] = useState(""); const [description, setDescription] = useState(""); const [requirements, setRequirements] = useState(""); const [expectedOutput, setExpectedOutput] = useState(""); const [criteria, setCriteria] = useState(""); const [mode, setMode] = useState<CourseAssignment["mode"]>("instruction"); const [minutes, setMinutes] = useState("20"); const [required, setRequired] = useState(true); const [role, setRole] = useState<AssignmentCoverageRole>("assess"); const [workflowTemplateId, setWorkflowTemplateId] = useState("");
  const create = () => { if (!title.trim() || !description.trim() || !expectedOutput.trim()) return; const assignmentId = `assignment-${crypto.randomUUID()}`; const assignment: CourseAssignment = { id: assignmentId, courseId, order: assignments.length, title: title.trim(), description: description.trim(), requirements: splitLines(requirements), expectedOutput: expectedOutput.trim(), acceptanceCriteria: splitLines(criteria), mode, estimatedMinutes: Math.max(1, Number(minutes) || 1), workflowTemplateId: mode === "workflow" && workflowTemplateId.trim() ? workflowTemplateId.trim() : undefined, experience: { type: "answer", prompt: description.trim() } }; const coverage: AssignmentCoverage = { id: `${assignmentId}:coverage:${knowledgeId}`, assignmentId, nodeId: knowledgeId, role, required }; onChange([...assignments, assignment], [...coverages, coverage]); setTitle(""); setDescription(""); setRequirements(""); setExpectedOutput(""); setCriteria(""); };
  const edit = (assignment: CourseAssignment) => { const nextTitle = window.prompt("实训标题", assignment.title); if (!nextTitle?.trim()) return; const nextDescription = window.prompt("目标与说明", assignment.description); if (!nextDescription?.trim()) return; const nextOutput = window.prompt("预期输出", assignment.expectedOutput); if (!nextOutput?.trim()) return; onChange(assignments.map((item) => item.id === assignment.id ? { ...item, title: nextTitle.trim(), description: nextDescription.trim(), expectedOutput: nextOutput.trim() } : item), coverages); };
  const remove = (assignmentId: string) => onChange(assignments.filter((assignment) => assignment.id !== assignmentId), coverages.filter((coverage) => coverage.assignmentId !== assignmentId));
  const move = (assignment: CourseAssignment, delta: number) => { const index = assignments.findIndex((item) => item.id === assignment.id); const target = index + delta; if (target < 0 || target >= assignments.length) return; const next = [...assignments]; [next[index], next[target]] = [next[target], next[index]]; onChange(next.map((item, order) => ({ ...item, order })), coverages); };
  return <section className="atlas-drawer-section"><h3>Assignment 编辑器</h3><p>Assignment 与 AssignmentCoverage 都是草稿投影；提交和验收生命周期保持独立。</p><div className="course-authoring-field"><input value={title} onChange={(event) => setTitle(event.target.value)} placeholder="实训标题" /><textarea value={description} onChange={(event) => setDescription(event.target.value)} placeholder="目标 / 说明" /><textarea value={requirements} onChange={(event) => setRequirements(event.target.value)} placeholder="要求：每行一项" /><input value={expectedOutput} onChange={(event) => setExpectedOutput(event.target.value)} placeholder="预期输出" /><textarea value={criteria} onChange={(event) => setCriteria(event.target.value)} placeholder="验收标准：每行一项" /><div className="course-authoring-inline-actions"><select value={mode} onChange={(event) => setMode(event.target.value as CourseAssignment["mode"])}><option value="instruction">instruction</option><option value="workflow">workflow</option></select><select value={role} onChange={(event) => setRole(event.target.value as AssignmentCoverageRole)}><option value="practice">practice</option><option value="apply">apply</option><option value="assess">assess</option></select><input type="number" min="1" value={minutes} onChange={(event) => setMinutes(event.target.value)} aria-label="预计分钟" /><label><input type="checkbox" checked={required} onChange={(event) => setRequired(event.target.checked)} />必修</label></div>{mode === "workflow" ? <input value={workflowTemplateId} onChange={(event) => setWorkflowTemplateId(event.target.value)} placeholder="Workflow template ID" /> : null}<button onClick={create}>创建 Assignment</button></div>{linked.length ? <div className="atlas-assignment-switcher">{linked.map((assignment) => { const coverage = coverages.find((item) => item.assignmentId === assignment.id && item.nodeId === knowledgeId)!; return <div className="atlas-assignment-row" key={assignment.id}><span>{assignment.order + 1}</span><strong>{assignment.title}<small>{assignment.mode} · {coverage.role} · {coverage.required ? "必修" : "选修"}</small></strong><button onClick={() => edit(assignment)}>编辑</button><button disabled={assignment.order === 0} onClick={() => move(assignment, -1)}>↑</button><button disabled={assignment.order === assignments.length - 1} onClick={() => move(assignment, 1)}>↓</button><button className="danger" onClick={() => remove(assignment.id)}>删除</button></div>; })}</div> : <p>当前 Knowledge 尚无 AssignmentCoverage。</p>}</section>;
}
