import { useEffect, useMemo, useState } from 'react';
import { ApiRequestError } from '@/shared/api/apiClient';
import { useNavigate } from 'react-router-dom';
import { ConversationWorkspace, type ConversationItem } from '@/features/assistant/conversation/ConversationWorkspace';
import { orderedWorkspaceReferences } from '@/features/assistant/conversation/workspaceReferences';
import { useWorkspaceConversation } from '@/features/assistant/conversation/useWorkspaceConversation';
import { evidenceRequest, readEvidenceLibrary, readEvidenceRun, uploadEvidence, type EvidenceProposal, type EvidenceRunDetail, type EvidenceSourceSummary, type EvidenceUploadProgress } from './evidenceClient';
import { pendingRunProposals, supportedConfirmationBatch, readyEvidenceSelection } from './confirmationSelection';
import { useEvidenceWorkspace } from './EvidenceWorkspace';

const errorText = (error: unknown) => error instanceof Error ? error.message : '本次操作未完成，请重试。';
type Conversation = ReturnType<typeof useWorkspaceConversation>;
export function CapabilityConversation({ courseId, sourceId, initialSourceIds = [], initialRunId, conversation, prefix = [], onContextChange }: {
  courseId?: string; sourceId?: string; initialSourceIds?: string[]; initialRunId?: string; conversation?: Conversation; prefix?: ConversationItem[];
  onContextChange?: (selection: {sourceId?:string;runId?:string}) => void;
}) {
  const environment = useEvidenceWorkspace()!; const navigate = useNavigate();
  const context = useMemo(() => ({ workspace:'learning' as const,experienceMode:'learn' as const,presentation:'capability-update',courseId,evidenceSourceId:sourceId,diagnosisRunId:initialRunId }),[courseId,sourceId,initialRunId]);
  const localConversation = useWorkspaceConversation('capability-update',context,!conversation);
  const chat = conversation ?? localConversation;
  const [sourcesLoaded,setSourcesLoaded]=useState(false);
  const [sources,setSources] = useState<EvidenceSourceSummary[]>([]);
  const [selected,setSelected] = useState<string[]>(() => [...new Set([...(sourceId?[sourceId]:[]),...initialSourceIds])]);
  const [runId,setRunId] = useState<string | undefined>(initialRunId); const [run,setRun] = useState<EvidenceRunDetail>();
  const [chosen,setChosen] = useState<string[]>([]); const [busy,setBusy] = useState(false); const [analyzing,setAnalyzing] = useState(false); const [error,setError] = useState('');
  const [retry,setRetry]=useState<(()=>void)>();
  const restoredAttachments=useMemo(()=>({done:false}),[]);
  const [supplement,setSupplement] = useState<string>(); const [confirmed,setConfirmed] = useState(false);
  const refs=orderedWorkspaceReferences(chat.messages,chat.references);
  const attachments=refs.filter(ref=>ref.event==='attachment').map(ref=>ref.referenceId);const attachmentsKey=JSON.stringify(attachments);
  const savedRunId=[...refs].reverse().find(ref=>['diagnosis','confirmation'].includes(ref.event))?.referenceId;
  useEffect(() => { let live=true; void readEvidenceLibrary().then(data=>{if(live){setSources(data.sources);setSourcesLoaded(true);}}).catch(error=>{if(live){setError(errorText(error));setRetry(()=>()=>void reloadSources());}}); return()=>{live=false;}; },[environment.revision]);
  useEffect(()=>{if(chat.loading||!sourcesLoaded||restoredAttachments.done)return;restoredAttachments.done=true;const ids=JSON.parse(attachmentsKey) as string[];setSelected(current=>[...new Set([...current,...ids])].filter(id=>sources.some(source=>source.id===id&&!source.archived_at)).slice(-5));},[attachmentsKey,chat.loading,restoredAttachments,sources,sourcesLoaded]);
  useEffect(()=>{if(savedRunId&&!initialRunId)setRunId(savedRunId);},[savedRunId,initialRunId]);
  useEffect(()=>{if(!runId)return;let live=true;setRun(undefined);setChosen([]);void readEvidenceRun(runId).then(data=>{if(live){setRun(data);setSelected(data.run.source_ids);setConfirmed(data.proposals.some(proposal=>proposal.confirmation_state==='confirmed'));}}).catch(error=>{if(live){if(error instanceof ApiRequestError&&error.status===404){chat.discardReference(runId);setRunId(undefined);}setError(errorText(error));setRetry(()=>()=>void refresh());}});return()=>{live=false;};},[runId]);
  useEffect(()=>{onContextChange?.({sourceId:selected.length===1?selected[0]:undefined,runId});},[onContextChange,selected,runId]);
  const proposals = run?.run.status === 'completed' ? run.proposals.filter(proposal=>proposal.run_id===runId) : [];
  const pending = pendingRunProposals(proposals,runId??null);
  const sameSources = Boolean(run && run.run.source_ids.length===selected.length && run.run.source_ids.every(id=>selected.includes(id)));
  const unavailable = selected.filter(id=>!sources.some(source=>source.id===id&&!source.archived_at));
  const eligible = selected.length>0&&selected.length<=5&&readyEvidenceSelection(selected,sources).length===selected.length;
  async function reloadSources(){try{setSources((await readEvidenceLibrary()).sources);setSourcesLoaded(true);setError('');}catch(error){setError(errorText(error));}}
  async function upload(file:File, isSupplement=false,progress:EvidenceUploadProgress={}) {
    if(selected.length>=5&&!progress.upload){setError('本次最多分析5份资料，请先取消选择一份后再上传。');return;}setBusy(true);setError('');setRetry(()=>()=>void upload(file,isSupplement,progress));try {const id=await uploadEvidence(file,{courseId,supplement:isSupplement},progress);await chat.record('attachment',id);const library=await readEvidenceLibrary();setSources(library.sources);setSelected(current=>[...new Set([...current,id])].slice(-5));setChosen([]);setConfirmed(false);environment.changed();return id;}catch(error){setError(errorText(error));}finally{setBusy(false);}
  }
  async function diagnose(ids=selected) {
    if(!ids.length||busy||!chat.sessionId)return;setBusy(true);setAnalyzing(true);setError('');setChosen([]);setConfirmed(false);setRetry(()=>()=>void diagnose(ids));
    try {const result=await evidenceRequest<{runId:string}>({action:'diagnose',sourceIds:ids});setRunId(result.runId);await chat.record('diagnosis',result.runId);environment.changed();}
    catch(error) {if(error instanceof ApiRequestError){const failed=(error.details as {runId?:string}|undefined)?.runId;if(failed){setRunId(failed);await chat.record('diagnosis',failed);}}if(!(error instanceof ApiRequestError&&(error.details as {runId?:string}|undefined)?.runId))setError(`${errorText(error)} 正式能力和路线没有改变。`);environment.changed();}
    finally {setBusy(false);setAnalyzing(false);}
  }
  async function refresh() {if(!runId)return;setBusy(true);setError('');try{setRun(await readEvidenceRun(runId));}catch(error){setError(errorText(error));}finally{setBusy(false);}}
  async function resolve(action:'confirm'|'reject') {
    const batch=pending.filter(proposal=>chosen.includes(proposal.id));if(!runId||!sameSources||!batch.length||!chat.sessionId)return;
    setBusy(true);setError('');setRetry(()=>()=>void resolve(action));try{await evidenceRequest({action,runId,proposalIds:batch.map(proposal=>proposal.id)});if(action==='confirm'){setConfirmed(true);await chat.record('confirmation',runId);await environment.confirmed().catch(()=>setError('本次能力更新已正式确认，状态显示暂未刷新，请重读本次结果。'));}else environment.changed();setRun(await readEvidenceRun(runId));setChosen([]);}catch(error){setError(errorText(error));}finally{setBusy(false);}
  }
  async function submitSupplement(file=new File([supplement??''],'本人补充工作说明.txt',{type:'text/plain'}),progress:EvidenceUploadProgress={},originalIds=selected) {if(!supplement||!chat.sessionId)return;const id=await upload(file,true,progress);if(id){setSupplement(undefined);await diagnose([...new Set([...originalIds,id])].slice(-5));}else setRetry(()=>()=>void submitSupplement(file,progress,originalIds));}
  const latestUser = [...chat.messages].reverse().find(message=>message.role==='user'&&!message.structuredContent)?.content;
  const runMessage:ConversationItem|undefined=run?{id:`run-${run.run.id}`,role:'assistant',content:<><small>{new Date(run.run.created_at).toLocaleString('zh-CN')}</small>{run.run.status==='failed'?<><h3>本次分析未完成</h3><p>正式能力和路线没有变化。</p><div className="workbench-actions"><button className="atlas-primary" disabled={busy||!eligible||!chat.sessionId} onClick={()=>void diagnose()}>重新分析</button></div><details><summary>技术详情</summary><p>{run.run.error??'分析未完成'}</p><small>Run ID：{run.run.id}</small></details></>:run.run.status==='running'?<><h3>正在分析本次资料</h3><p>正式能力和路线没有变化。</p><button className="atlas-secondary" disabled={busy} onClick={()=>void refresh()}>刷新状态</button><details><summary>技术详情</summary><small>Run ID：{run.run.id}</small></details></>:<><h3>{proposals.length?'我发现以下能力候选':'本次没有可更新的能力候选'}</h3><p>可以查看依据、继续追问或补充真实材料。候选不是正式能力。</p>{!sameSources?<p role="status">资料选择已变化。请开始新的分析后再确认。</p>:null}<div className="evidence-candidate-list">{proposals.map(proposal=><ProposalCard key={proposal.id} proposal={proposal} run={run} title={environment.nodeTitle} selected={chosen.includes(proposal.id)} disabled={busy||!sameSources||proposal.confirmation_state!=='pending'||!proposal.proposed_status||(!chosen.includes(proposal.id)&&chosen.length>=50)} onSelect={value=>{setRetry(undefined);setChosen(current=>value?[...current,proposal.id]:current.filter(id=>id!==proposal.id));}}/>)}</div>{pending.length&&sameSources?<><button className="atlas-secondary" disabled={busy} onClick={()=>{setRetry(undefined);setChosen(supportedConfirmationBatch(proposals,runId??null));}}>选择证据充分的候选</button><div className="workbench-actions"><button className="atlas-secondary" disabled={busy||!chosen.length||!chat.sessionId} onClick={()=>void resolve('reject')}>排除所选候选</button><button className="atlas-primary" disabled={busy||!chosen.length||!chat.sessionId} onClick={()=>void resolve('confirm')}>确认本次能力更新 · {chosen.length} 项</button></div></>:null}<details><summary>技术详情</summary><small>Run ID：{run.run.id}</small></details></>}</>}:undefined;
  const messages: ConversationItem[] = [...prefix,{id:'capability-intro',role:'assistant',content:<><p>把你做过的工作资料发给我。我会检查其中能证明哪些能力，再由你明确确认。</p><p>对话只是讨论；普通消息与我的回复不会进入能力证据。</p><small>支持 TXT、Markdown、CSV。上传资料不会自动更新能力。</small></>},...chat.messages.map(message=>({id:message.id,role:message.role,content:message.structuredContent?.type==='workspace_event'?<><p>{message.content}</p>{message.structuredContent.event==='diagnosis'&&message.structuredContent.referenceId===runId?runMessage?.content:null}<small>{message.structuredContent.event==='attachment' ? sources.find(source=>source.id===(message.structuredContent?.type==='workspace_event'?message.structuredContent.referenceId:undefined))?.title??'已保存资料' : message.structuredContent.event==='confirmation'?'能力更新确认记录':'独立分析记录'}</small>{['diagnosis','confirmation'].includes(message.structuredContent.event)&&message.structuredContent.referenceId!==runId?<HistoricalRun id={message.structuredContent.referenceId} title={environment.nodeTitle}/>:null}</>:message.content}))];
  messages.push({id:'source-selection',role:'assistant',content:<details><summary>本次资料 · 已选择 {selected.length} 份</summary><div className="evidence-source-picker">{unavailable.map(id=><p key={id} role="status">原分析资料已归档或无法读取<button className="atlas-secondary" disabled={busy} onClick={()=>{setRetry(undefined);setSelected(current=>current.filter(value=>value!==id));setChosen([]);setConfirmed(false);}}>取消选择</button></p>)}{sources.filter(source=>!source.archived_at).map(source=><label className="evidence-card" key={source.id}><input type="checkbox" checked={selected.includes(source.id)} disabled={busy||source.parse_status!=='ready'||(!selected.includes(source.id)&&selected.length>=5)} onChange={event=>{setRetry(undefined);setSelected(current=>event.target.checked?[...current,source.id]:current.filter(id=>id!==source.id));setChosen([]);setConfirmed(false);}}/><span>{source.title}<small>{source.parse_status==='ready'?'已保存并解析':'等待上传 / 解析'}</small></span></label>)}</div></details>});
  if(runMessage&&!chat.messages.some(message=>message.structuredContent?.type==='workspace_event'&&message.structuredContent.event==='diagnosis'&&message.structuredContent.referenceId===runId))messages.push(runMessage);
  if(analyzing)messages.push({id:'analysis-status',role:'assistant',content:<><strong>正在分析本次资料…</strong><p>检查实际过程与结果，保留独立的分析记录。正式能力和路线没有改变。</p></>});

  if(supplement)messages.push({id:'supplement-confirm',role:'assistant',content:<><p>这段内容将作为本人提交的工作说明进入新的能力分析，旧分析记录保持不变。</p><blockquote>{supplement}</blockquote><button className="atlas-primary" disabled={busy} onClick={()=>void submitSupplement()}>确认作为本人补充材料并重新分析</button><button className="atlas-secondary" disabled={busy} onClick={()=>setSupplement(undefined)}>取消</button></>});
  if(confirmed)messages.push({id:'route-impact',role:'assistant',content:<><h3>本次能力更新已确认</h3><p>能力状态已经更新。当前正式路线没有自动修改，路线版本没有增加。</p>{courseId?<><p>{environment.preview(courseId,proposals.filter(proposal=>proposal.confirmation_state==='confirmed'))}</p><button className="atlas-secondary" onClick={()=>{environment.close();navigate(`/courses/${encodeURIComponent(courseId)}?view=project&routeImpact=1`);}}>查看路线建议</button><small>将进入项目路线 Preview；只有明确采用才会更新正式路线。</small></>:<p>可以前往课程项目能力模型查看新的路线机会。</p>}</>});
  return <ConversationWorkspace mode="capability-update" messages={messages} loading={chat.loading} sending={busy||chat.sending||chat.loading} composerDisabled={!chat.sessionId} error={error||chat.error} onRetry={error?retry??(()=>void refresh()):chat.retry} onSend={text=>{setRetry(()=>()=>void chat.send(text,{...context,diagnosisRunId:runId,evidenceSourceId:selected.length===1?selected[0]:undefined}));return chat.send(text,{...context,diagnosisRunId:runId,evidenceSourceId:selected.length===1?selected[0]:undefined});}} onAttachment={file=>void upload(file)} composerActions={<>{run?.run.status!=='failed'?<button className="atlas-primary" disabled={busy||!eligible||!chat.sessionId||run?.run.status==='running'} onClick={()=>void diagnose()}>分析本次资料</button>:null}{latestUser?<button className="atlas-secondary" disabled={busy} onClick={()=>setSupplement(latestUser)}>将最近说明作为补充材料</button>:null}</>}/>;
}
function ProposalCard({proposal,run,title,selected,disabled,onSelect}:{proposal:EvidenceProposal;run:EvidenceRunDetail;title:(id:string)=>string;selected:boolean;disabled:boolean;onSelect:(value:boolean)=>void}) {
  const label=proposal.node_id?title(proposal.node_id):'尚未匹配能力';
  return <article className="evidence-card"><label><input type="checkbox" aria-label={`选择 ${label}`} checked={selected} disabled={disabled} onChange={event=>onSelect(event.target.checked)}/><strong>{label}</strong></label><p>{proposal.sufficiency==='supported'?'✓ 证据充分':proposal.sufficiency==='partial'?'? 依据不完整':'× 依据不足'} · {Math.round(proposal.confidence*100)}% · {proposal.confirmation_state==='confirmed'?'已确认':proposal.confirmation_state==='rejected'?'已排除':'待确认'}</p><details><summary>查看判断与原始依据</summary><p>{proposal.reason}</p>{run.units.filter(unit=>proposal.unit_ids.includes(unit.id)).map(unit=><blockquote key={unit.id}><small>{run.sources.find(source=>source.id===unit.source_id)?.title} · 第 {unit.source_line} 行</small><p>{unit.quote}</p></blockquote>)}</details></article>;
}

function HistoricalRun({id,title}:{id:string;title:(id:string)=>string}){const [detail,setDetail]=useState<EvidenceRunDetail>();const [error,setError]=useState('');async function load(){try{setDetail(await readEvidenceRun(id));setError('');}catch(error){setError(errorText(error));}}return <details onToggle={event=>{if(event.currentTarget.open&&!detail)void load();}}><summary>历史分析 · 查看原始记录</summary><p>历史依据与结论保持独立；当前确认只属于当前分析。</p>{error?<p role="alert">{error}<button onClick={()=>void load()}>重试读取</button></p>:null}{detail?<><p>{detail.run.status} · {new Date(detail.run.created_at).toLocaleString('zh-CN')}</p>{detail.proposals.map(proposal=><ProposalCard key={proposal.id} proposal={proposal} run={detail} title={title} selected={false} disabled onSelect={()=>undefined}/>)}</>:<p>正在读取历史记录…</p>}</details>;}

export function CapabilityWorkbenchContext(){return <><section><h3>能力更新上下文</h3><p>提供本人已完成工作的过程、计算依据、结果与边界。</p></section><section><h3>支持资料格式</h3><p>TXT、Markdown、CSV。每份最多 24,000 字符，每次最多 5 份。</p></section><section><h3>当前正式状态</h3><p>上传与分析只产生资料和能力候选，最后需要你明确确认。</p></section><section><h3>重要规则</h3><p>普通聊天与 Assistant 回复不等于 Evidence。</p><p>确认能力不会自动修改正式路线。查看建议先进入 Preview，只有 Adopt 才追加正式版本。</p></section></>;}
