import { createContext, useCallback, useContext, useEffect, useRef, useState, type ReactNode } from 'react';
import { AnimatePresence, motion, useReducedMotion } from 'motion/react';
import { X, Upload, FileText, ArrowLeft, Check, Loader2 } from 'lucide-react';
import { evidenceRequest, readEvidenceLibrary, readEvidenceSource, readEvidenceRun, readEvidenceHistory, uploadEvidence, type EvidenceSourceSummary, type EvidenceSourceDetail, type EvidenceRunDetail, type EvidenceHistory, type EvidenceProposal } from './evidenceClient';
import { CONFIRMATION_BATCH_LIMIT, pendingRunProposals, supportedConfirmationBatch, readyEvidenceSelection } from './confirmationSelection';
import './evidence.css';

type EvidenceSelection={sourceId?:string;runId?:string};
type Workspace=EvidenceSelection & {courseId?:string};
type EvidenceEnvironment={surfaceHost?:HTMLElement|null;foreground?:Workspace;revision:number;changed:()=>void;open:(courseId?:string,sourceId?:string,runId?:string)=>void;close:()=>void;confirmed:()=>Promise<void>;nodeTitle:(id:string)=>string;preview:(courseId:string,proposals:EvidenceProposal[])=>string};
const EvidenceContext=createContext<EvidenceEnvironment|null>(null);
export const useEvidenceWorkspace=()=>useContext(EvidenceContext);
const dateLabel=(value:string)=>new Date(value).toLocaleString('zh-CN');
const runLabel={running:'分析中',completed:'分析完成',failed:'分析未完成'};
const parseLabel=(source:EvidenceSourceSummary)=>source.archived_at?'已归档':source.parse_status==='ready'?'已解析':source.parse_status==='failed'?'解析失败':'等待上传 / 解析';
const errorText=(error:unknown)=>error instanceof Error?error.message:'操作暂未完成，请重试。';

export function EvidenceWorkspaceProvider({children,onConfirmed,nodeTitle,preview}:{children:ReactNode;onConfirmed:()=>Promise<void>;nodeTitle:(id:string)=>string;preview:EvidenceEnvironment['preview']}) {
 const [surfaceHost,setSurfaceHost]=useState<HTMLDivElement|null>(null);
 const [selection,setSelection]=useState<EvidenceSelection>({});
 const [workspace,setWorkspace]=useState<Workspace|null>(null);
 const [revision,setRevision]=useState(0);const changed=useCallback(()=>setRevision(value=>value+1),[]);
 const dialog=useRef<HTMLDialogElement>(null);const workspaceOpen=useRef(false);workspaceOpen.current=Boolean(workspace);const reduced=useReducedMotion();
 const open=useCallback((courseId?:string,sourceId?:string,runId?:string)=>{setSelection({sourceId,runId});setWorkspace({courseId,sourceId,runId});},[]);
 const close=useCallback(()=>{setWorkspace(null);changed();},[changed]);
 useEffect(()=>{if(workspace&&!dialog.current?.open)dialog.current?.showModal();},[workspace]);
 const confirmed=async()=>{await onConfirmed();changed();};
 return <EvidenceContext.Provider value={{open,close,confirmed,nodeTitle,preview,revision,changed,surfaceHost:workspace?surfaceHost:null,foreground:workspace?{courseId:workspace.courseId,...selection}:undefined}}>{children}
  <dialog ref={dialog} className="capability-workspace" onCancel={event=>{event.preventDefault();close();}} aria-labelledby="capability-workspace-title">
   <AnimatePresence onExitComplete={()=>{if(!workspaceOpen.current)dialog.current?.close();}}>{workspace?<motion.div key="workspace" initial={{opacity:0,y:reduced?0:12}} animate={{opacity:1,y:0}} exit={{opacity:0,y:reduced?0:12}} transition={{duration:reduced?0:.24}} className="capability-workspace-content">
    <header className="capability-workspace-header"><div><span className="evidence-eyebrow">个人能力</span><h1 id="capability-workspace-title">更新我的能力</h1><p>从真实资料中检查能力依据，再决定是否更新。</p></div><button className="evidence-icon-button" aria-label="关闭能力更新工作区" onClick={close}><X size={20}/></button></header>
    <CapabilityDiagnosis key={`${workspace.courseId??''}:${workspace.sourceId??''}:${workspace.runId??''}`} workspace={workspace} onContextChange={setSelection}/>
   </motion.div>:null}</AnimatePresence>
   <div ref={setSurfaceHost} className="evidence-assistant-host"/>
  </dialog>
 </EvidenceContext.Provider>;
}

function UploadSource({busy,onUpload,secondary=false}:{busy:boolean;onUpload:(file:File)=>void;secondary?:boolean}) {
 const input=useRef<HTMLInputElement>(null);
 return <><button className={secondary?"atlas-secondary":"atlas-primary"} disabled={busy} onClick={()=>input.current?.click()}><Upload size={16}/>上传资料</button><input ref={input} className="evidence-file-input" aria-label="上传证据资料" type="file" accept=".txt,.md,.csv" disabled={busy} onChange={event=>{const file=event.target.files?.[0];if(file)onUpload(file);event.target.value='';}}/></>;
}
function FormatHint(){return <p className="evidence-format">支持 TXT、Markdown、CSV，每份最多 24,000 字符。请提供本人已完成工作的过程与结果；计划或教材不代表已经具备能力。</p>;}
function Feedback({error,message}:{error?:string;message?:string}) {return <>{error?<p role="alert" className="evidence-error">{error}</p>:null}{message?<p role="status" className="evidence-success">{message}</p>:null}</>;}

function SourceDetail({sourceId,onBack,onRun}:{sourceId:string;onBack:()=>void;onRun:(id:string)=>void}) {
 const environment=useEvidenceWorkspace()!;const [data,setData]=useState<EvidenceSourceDetail|null>(null);const [error,setError]=useState('');const [downloading,setDownloading]=useState(false);
 useEffect(()=>{let live=true;setData(null);setError('');void readEvidenceSource(sourceId).then(value=>{if(live)setData(value);}).catch(error=>{if(live)setError(errorText(error));});return()=>{live=false;};},[sourceId,environment.revision]);
 async function download(){const popup=window.open('','_blank');if(!popup){setError('浏览器未能打开文件窗口，请允许此站点打开新窗口后重试。');return;}popup.opener=null;setDownloading(true);try{const {url}=await evidenceRequest<{url:string}>({action:'download',sourceId});popup.location.href=url;}catch(error){popup.close();setError(errorText(error));}finally{setDownloading(false);}}
 return <section className="evidence-source-detail" aria-label="资料详情"><button className="evidence-text-button" onClick={onBack}><ArrowLeft size={15}/>返回资料库</button><Feedback error={error}/>{!data&&!error?<p role="status">正在读取资料详情…</p>:data?<>
  <header><div><span className="evidence-eyebrow">原始资料与能力依据</span><h2>{data.source.title}</h2><p>{dateLabel(data.source.created_at)}</p></div><button className="atlas-secondary" disabled={downloading} onClick={()=>void download()}>打开原始文件</button></header>
  <details className="evidence-card"><summary>查看原文解析</summary><pre>{data.source.parsed_lines.map(line=>`${line.line}  ${line.text}`).join('\n')||'尚无可读取的解析内容。'}</pre></details>
  <div className="evidence-detail-columns"><section><h3>证据片段 · {data.units.length}</h3>{!data.units.length?<p>尚未从这份资料中提取能力表现。</p>:data.units.map(unit=><article className="evidence-card" key={unit.id}><small>原文第 {unit.source_line} 行</small><blockquote>{unit.quote}</blockquote><strong>{unit.capability}</strong><p>{unit.observation}</p>{data.proposals.filter(proposal=>proposal.unit_ids.includes(unit.id)).map(proposal=><p key={proposal.id}><strong>{proposal.node_id?environment.nodeTitle(proposal.node_id):'尚未匹配能力'}</strong> · {proposal.confirmation_state==='confirmed'?'已产生正式确认':proposal.confirmation_state==='rejected'?'已拒绝':'尚未确认'}<button className="evidence-text-button" onClick={()=>onRun(proposal.run_id)}>查看本次判断</button></p>)}</article>)}</section>
  <section><h3>参与过的能力分析 · {data.runs.length}</h3>{!data.runs.length?<p>还未用于能力判断。</p>:data.runs.map(run=><button className="evidence-history-row" key={run.id} onClick={()=>onRun(run.id)}><strong>{runLabel[run.status]}</strong><span>{dateLabel(run.created_at)}</span><small>{run.source_ids.length} 份资料 · 查看候选与确认记录</small></button>)}</section></div>
 </>:null}</section>;
}

export function EvidenceLibrary({onContextChange}:{onContextChange?:(selection:EvidenceSelection)=>void}) {
 const environment=useEvidenceWorkspace()!;const [sources,setSources]=useState<EvidenceSourceSummary[]>([]);const [detail,setDetail]=useState<string|null>(null);const [historyOpen,setHistoryOpen]=useState(false);const [history,setHistory]=useState<EvidenceHistory>({runs:[],nextCursor:null});
 const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [message,setMessage]=useState('');
 useEffect(()=>{onContextChange?.({sourceId:detail??undefined});},[detail,onContextChange]);
 useEffect(()=>{let live=true;setLoading(true);void readEvidenceLibrary().then(value=>{if(live)setSources(value.sources);}).catch(error=>{if(live)setError(errorText(error));}).finally(()=>{if(live)setLoading(false);});return()=>{live=false;};},[environment.revision]);
 async function upload(file:File){setBusy(true);setError('');try{const id=await uploadEvidence(file);environment.changed();setDetail(id);setMessage('资料已保存并完成解析。');}catch(error){setError(errorText(error));environment.changed();}finally{setBusy(false);}}
 async function loadHistory(cursor?:string){setBusy(true);setError('');try{const value=await readEvidenceHistory(cursor);setHistory(current=>({runs:cursor?[...current.runs,...value.runs]:value.runs,nextCursor:value.nextCursor}));setHistoryOpen(true);setDetail(null);}catch(error){setError(errorText(error));}finally{setBusy(false);}}
 async function archive(id:string){setBusy(true);setError('');try{await evidenceRequest({action:'archive',sourceId:id});environment.changed();setMessage('资料已归档，正式确认记录仍然保留。');}catch(error){setError(errorText(error));}finally{setBusy(false);}}
 return <div className="evidence-library"><header className="evidence-library-header"><div><span className="evidence-eyebrow">个人资料库</span><h1>我的证据</h1><p>保存做过的工作，追溯能力判断的来源。</p></div><div className="evidence-actions"><UploadSource busy={busy} onUpload={file=>void upload(file)}/><button className="atlas-secondary" onClick={()=>environment.open()}>更新我的能力</button></div></header>
  <FormatHint/><Feedback error={error} message={message}/>
  {detail?<SourceDetail sourceId={detail} onBack={()=>setDetail(null)} onRun={id=>environment.open(undefined,detail,id)}/>:historyOpen?<section aria-label="能力分析历史"><button className="evidence-text-button" onClick={()=>setHistoryOpen(false)}><ArrowLeft size={15}/>返回资料库</button><h2>能力分析历史</h2><p>每次分析独立保存。打开某次分析，查看它的资料、候选和确认结果。</p>{history.runs.length?history.runs.map(run=><button className="evidence-history-row" key={run.id} onClick={()=>environment.open(undefined,undefined,run.id)}><strong>{runLabel[run.status]}</strong><span>{dateLabel(run.created_at)}</span><small>{run.source_ids.length} 份资料</small></button>):<p>还没有能力分析记录。</p>}{history.nextCursor?<button className="atlas-secondary" disabled={busy} onClick={()=>void loadHistory(history.nextCursor!)}>加载更早记录</button>:null}</section>:<>
   <div className="evidence-section-heading"><h2>资料 · {sources.length}</h2><button className="evidence-text-button" disabled={busy} onClick={()=>void loadHistory()}>查看能力分析历史</button></div>
   {loading?<p role="status">正在读取资料摘要…</p>:!sources.length?<div className="evidence-empty"><FileText size={32}/><h3>先保存一份真实工作资料</h3><p>可以是任务复盘、项目记录或带有结果的操作说明。上传不会自动更新能力。</p></div>:<div className="evidence-source-grid">{sources.map(source=><article className={`evidence-card ${source.archived_at?'archived':''}`} key={source.id}><div className="evidence-card-title"><FileText size={18}/><h3>{source.title}</h3><span className="evidence-status">{parseLabel(source)}</span></div><small>{dateLabel(source.created_at)} · {source.provenance.kind==='user-upload'?'本人上传':'执行资料'}</small><dl><div><dt>用于能力判断</dt><dd>{source.diagnosisCount?`${source.diagnosisCount} 次`:'尚未使用'}</dd></div><div><dt>关联能力</dt><dd>{source.capabilityCount} 项</dd></div><div><dt>正式确认</dt><dd>{source.confirmedCount} 项</dd></div></dl>{source.parse_error?<p className="evidence-error">{source.parse_error}</p>:null}<div className="evidence-actions"><button className="atlas-secondary" onClick={()=>setDetail(source.id)}>查看资料与依据</button>{!source.archived_at?<button className="evidence-text-button" disabled={busy} onClick={()=>void archive(source.id)}>归档</button>:null}</div></article>)}</div>}
  </>}
 </div>;
}

function CapabilityDiagnosis({workspace,onContextChange}:{workspace:Workspace;onContextChange:(selection:EvidenceSelection)=>void}) {
 const environment=useEvidenceWorkspace()!;const [sources,setSources]=useState<EvidenceSourceSummary[]>([]);const [selected,setSelected]=useState<string[]>(workspace.sourceId?[workspace.sourceId]:[]);
 const [runId,setRunId]=useState<string|null>(workspace.runId??null);const [run,setRun]=useState<EvidenceRunDetail|null>(null);const [chosen,setChosen]=useState<string[]>([]);const [confirming,setConfirming]=useState(false);
 const [busy,setBusy]=useState(false);const [analyzing,setAnalyzing]=useState(false);const [sourcesLoading,setSourcesLoading]=useState(true);const [runLoading,setRunLoading]=useState(Boolean(workspace.runId));const [error,setError]=useState('');const [message,setMessage]=useState('');const [inspectSource,setInspectSource]=useState<string|null>(null);const activeRun=useRef(runId);activeRun.current=runId;const stageElement=useRef<HTMLDivElement>(null);const previousStep=useRef(1);
 useEffect(()=>{onContextChange({sourceId:inspectSource??(selected.length===1?selected[0]:undefined),runId:runId??undefined});},[inspectSource,selected,runId,onContextChange]);
 useEffect(()=>{let live=true;void readEvidenceLibrary().then(value=>{if(live)setSources(value.sources);}).catch(error=>{if(live)setError(errorText(error));}).finally(()=>{if(live)setSourcesLoading(false);});return()=>{live=false;};},[environment.revision]);
 useEffect(()=>{if(!runId){setRun(null);setRunLoading(false);return;}let live=true;setRun(null);setRunLoading(true);setError('');void readEvidenceRun(runId).then(value=>{if(live){setRun(value);setSelected(value.run.source_ids);}}).catch(error=>{if(live)setError(errorText(error));}).finally(()=>{if(live)setRunLoading(false);});return()=>{live=false;};},[runId]);
 const proposals=run?.run.status==='completed'?run.proposals.filter(proposal=>proposal.run_id===runId):[];
 const pending=pendingRunProposals(proposals,runId);
 const selectedProposals=pending.filter(proposal=>chosen.includes(proposal.id));
 const validSourceSelection=selected.length>0&&selected.length<=5&&readyEvidenceSelection(selected,sources).length===selected.length;
 const step=analyzing||run?.run.status==='running'?2:confirming?4:runId?3:1;
 useEffect(()=>{if(previousStep.current===step)return;previousStep.current=step;stageElement.current?.focus({preventScroll:true});stageElement.current?.scrollIntoView({block:'start',behavior:'instant'});},[step]);
 async function upload(file:File){setBusy(true);setError('');try{const id=await uploadEvidence(file);setSelected(ids=>[...ids,id]);environment.changed();}catch(error){setError(errorText(error));environment.changed();}finally{setBusy(false);}}
 async function diagnose(){if(!validSourceSelection)return;setBusy(true);setAnalyzing(true);setError('');setMessage('');try{const result=await evidenceRequest<{runId:string}>({action:'diagnose',sourceIds:selected});setRunId(result.runId);environment.changed();}catch(error){setError(errorText(error));environment.changed();}finally{setAnalyzing(false);setBusy(false);}}
 async function refresh(){if(!runId)return;const requestedRun=runId;setBusy(true);setRunLoading(true);setError('');try{const value=await readEvidenceRun(requestedRun);if(activeRun.current===requestedRun){setRun(value);setSelected(value.run.source_ids);}}catch(error){if(activeRun.current===requestedRun)setError(errorText(error));}finally{if(activeRun.current===requestedRun){setBusy(false);setRunLoading(false);}}}
 async function resolve(proposals:EvidenceProposal[],action:'confirm'|'reject') {
  if(!runId||!proposals.length||proposals.length>CONFIRMATION_BATCH_LIMIT||proposals.some(proposal=>proposal.run_id!==runId))return;
  setBusy(true);setError('');try{await evidenceRequest({action,runId,proposalIds:proposals.map(proposal=>proposal.id)});if(action==='confirm')await environment.confirmed();else environment.changed();const value=await readEvidenceRun(runId);if(activeRun.current===runId){setRun(value);setChosen([]);setMessage(action==='confirm'?'已确认本次能力更新。项目投影已刷新，路线版本没有自动增加。':'已拒绝所选候选。');}}catch(error){if(activeRun.current===runId)setError(errorText(error));}finally{if(activeRun.current===runId)setBusy(false);}
 }
 function reset(){setSelected([]);setRunId(null);setRun(null);setChosen([]);setConfirming(false);setError('');setMessage('');setInspectSource(null);}
 return <div className="capability-diagnosis"><ol className="evidence-steps" aria-label="能力更新进度">{['选择资料','分析资料','查看能力候选','确认更新'].map((title,index)=><li key={title} aria-current={step===index+1?'step':undefined} className={step>index+1?'done':''}><span>{step>index+1?<Check size={13}/>:index+1}</span>{title}</li>)}</ol>
  <p className="evidence-state-notice">确认前，你的能力和项目路线不会改变。</p><Feedback error={error} message={message}/>
  <div ref={stageElement} tabIndex={-1} className="evidence-stage" aria-label={step===1?'选择资料':step===2?'分析资料':step===3?'查看能力候选':'确认更新'}>{inspectSource?<SourceDetail sourceId={inspectSource} onBack={()=>setInspectSource(null)} onRun={id=>{setRunId(id);setInspectSource(null);setChosen([]);setConfirming(false);}}/>:analyzing?<div className="evidence-analyzing" role="status"><Loader2 className="spin" size={26}/><h2>正在分析这次选择的资料</h2><p>提取真实表现、匹配已有能力，再检查依据是否充分。</p><small>可以关闭工作区；分析记录会保存在“能力分析历史”。</small></div>:!runId?<>
   <div className="evidence-section-heading"><div><h2>用哪些资料更新能力？</h2><p>选择 1–5 份已解析的资料。</p></div><UploadSource busy={busy} secondary={sources.some(source=>!source.archived_at&&source.parse_status==='ready')} onUpload={file=>void upload(file)}/></div><FormatHint/>
   {sourcesLoading?<p role="status">正在读取可用资料…</p>:!sources.length?<div className="evidence-empty"><FileText size={30}/><h3>还没有可分析的资料</h3><p>上传工作记录后，再开始分析。</p></div>:<div className="evidence-source-picker">{sources.map(source=><label className={`evidence-card ${selected.includes(source.id)?'selected':''}`} key={source.id}><input type="checkbox" checked={selected.includes(source.id)} disabled={busy||(!selected.includes(source.id)&&(Boolean(source.archived_at)||source.parse_status!=='ready'||selected.length>=5))} onChange={event=>setSelected(ids=>event.target.checked?[...ids,source.id]:ids.filter(id=>id!==source.id))}/><span><strong>{source.title}</strong><small>{parseLabel(source)} · {dateLabel(source.created_at)}</small></span></label>)}</div>}
   <footer className="evidence-stage-actions"><span>已选 {selected.length} 份资料</span><button className="atlas-primary" disabled={busy||!validSourceSelection} onClick={()=>void diagnose()}>分析所选资料</button></footer>
  </>:runLoading?<p role="status">正在读取本次能力分析…</p>:run?<>
   <div className="evidence-run-heading"><div><span className="evidence-eyebrow">本次分析 · {dateLabel(run.run.created_at)}</span><h2>{confirming?'检查并确认更新':runLabel[run.run.status]}</h2><p>{run.sources.map(source=>source.title).join('、')}</p></div><button className="evidence-text-button" disabled={busy} onClick={reset}>选择其他资料</button></div>
   {run.run.status!=='completed'?<div className="evidence-card"><p>{run.run.error??'服务端仍在分析中。无需重复提交，可稍后刷新结果。'}</p><button className="atlas-secondary" disabled={busy} onClick={()=>void refresh()}>刷新本次结果</button></div>:<>
    {workspace.courseId&&proposals.length?<aside className="evidence-impact"><strong>项目影响预览 · 尚未写入</strong><p>{environment.preview(workspace.courseId,confirming?selectedProposals:pending)}</p></aside>:null}
    {!proposals.length?<div className="evidence-empty"><h3>本次没有可更新的能力候选</h3><p>资料已保存。可以补充实际过程和结果后再次分析。</p></div>:confirming?<><div className="evidence-confirm-summary">{selectedProposals.map(proposal=><article className="evidence-card" key={proposal.id}><strong>{environment.nodeTitle(proposal.node_id!)}</strong><p>确认后建议状态：{proposal.proposed_status==='learned'?'已学习':'学习中'}</p><p>{proposal.reason}</p></article>)}</div>{selectedProposals.length?<p>将仅确认这次分析中选中的 {selectedProposals.length} 项判断。</p>:<p>本次已没有选中且待确认的候选。可以返回查看结果。</p>}<footer className="evidence-stage-actions"><button className="atlas-secondary" disabled={busy} onClick={()=>setConfirming(false)}>返回查看候选</button><button className="atlas-primary" disabled={busy||!selectedProposals.length} onClick={()=>void resolve(selectedProposals,'confirm')}>{busy?'正在确认…':`确认 ${selectedProposals.length} 项能力更新`}</button></footer></>:<>
     <div className="evidence-section-heading"><p>候选来自本次分析；置信度不是正式能力状态。每批最多确认 50 项，余下候选可继续分批处理。</p>{pending.some(proposal=>proposal.sufficiency==='supported'&&Number(proposal.confidence)>=.85)?<button className="evidence-text-button" disabled={busy} onClick={()=>setChosen(supportedConfirmationBatch(proposals,runId))}>选择证据充分的候选（最多 50 项）</button>:null}</div>
     <div className="evidence-candidate-list">{proposals.map(proposal=><article className="evidence-card" key={proposal.id}><div className="evidence-candidate-heading"><input type="checkbox" aria-label={`选择 ${proposal.node_id?environment.nodeTitle(proposal.node_id):'未匹配候选'}`} checked={chosen.includes(proposal.id)} disabled={busy||proposal.confirmation_state!=='pending'||!proposal.proposed_status||(!chosen.includes(proposal.id)&&chosen.length>=CONFIRMATION_BATCH_LIMIT)} onChange={event=>setChosen(ids=>event.target.checked?[...ids,proposal.id]:ids.filter(id=>id!==proposal.id))}/><div><h3>{proposal.node_id?environment.nodeTitle(proposal.node_id):'尚未匹配已有能力'}</h3><small>{({supported:'证据充分',partial:'部分证据',insufficient:'证据不足',unmatched:'未匹配'} as const)[proposal.sufficiency]} · 置信度 {Math.round(Number(proposal.confidence)*100)}% · {proposal.proposed_status==='learned'?'建议已学习':proposal.proposed_status==='learning'?'建议学习中':'不更改状态'}</small></div></div><p>{proposal.reason}</p><details><summary>查看判断依据 · {proposal.unit_ids.length}</summary>{proposal.unit_ids.map(id=>{const unit=run.units.find(unit=>unit.id===id);return unit?<blockquote key={id}><p>{unit.quote}</p><small>{run.sources.find(source=>source.id===unit.source_id)?.title} · 第 {unit.source_line} 行</small><button className="evidence-text-button" disabled={busy} onClick={()=>setInspectSource(unit.source_id)}>查看这份资料</button></blockquote>:null;})}</details>{proposal.confirmation_state==='pending'?<button className="evidence-text-button" disabled={busy} onClick={()=>void resolve([proposal],'reject')}>拒绝这项判断</button>:<strong className="evidence-resolution">{proposal.confirmation_state==='confirmed'?'已正式确认':'已拒绝'}</strong>}</article>)}</div>
     <footer className="evidence-stage-actions"><span>已选择 {selectedProposals.length} 项</span><button className="atlas-primary" disabled={busy||!selectedProposals.length} onClick={()=>setConfirming(true)}>检查所选更新</button></footer>
    </>}
   </>}
  </>:<div className="evidence-stage-actions"><button className="atlas-secondary" disabled={busy} onClick={reset}>返回选择资料</button><button className="atlas-primary" disabled={busy} onClick={()=>void refresh()}>重试读取本次分析</button></div>}</div>
 </div>;
}
