import {beforeEach,expect,it,vi} from 'vitest';
const mocks=vi.hoisted(()=>({request:vi.fn(),upload:vi.fn()}));
vi.mock('@/shared/api/apiClient',()=>({apiRequest:mocks.request}));
vi.mock('@/shared/api/supabaseClient',()=>({supabaseClient:{storage:{from:()=>({uploadToSignedUrl:mocks.upload})}}}));
import {uploadEvidence,type EvidenceUploadProgress} from './evidenceClient';
beforeEach(()=>{mocks.request.mockReset();mocks.upload.mockReset().mockResolvedValue({error:null});mocks.request.mockImplementation(async(_path:string,options:{body:string})=>{const body=JSON.parse(options.body);return body.action==='upload'?{source:{id:'original-owned-source'},bucket:'user-evidence',path:'owner/source',token:'signed-private-token'}:{source:{id:body.sourceId}};});});
it('uploads actual original bytes through the private signed endpoint, parses them, and retains context',async()=>{const file=new File(['需求120，库存35，净需求85。'],'record.CSV');expect(await uploadEvidence(file,{courseId:'real-course',assignmentId:'real-assignment'})).toBe('original-owned-source');expect(mocks.upload).toHaveBeenCalledWith('owner/source','signed-private-token',file,{contentType:'text/csv'});expect(JSON.parse(mocks.request.mock.calls[0][1].body)).toMatchObject({action:'upload',size:file.size,courseId:'real-course',assignmentId:'real-assignment'});expect(JSON.parse(mocks.request.mock.calls[1][1].body)).toEqual({action:'parse',sourceId:'original-owned-source'});});
it('parse failure retries the same source without duplicate allocation or file upload',async()=>{let fail=true;mocks.request.mockImplementation(async(_path:string,options:{body:string})=>{const body=JSON.parse(options.body);if(body.action==='parse'&&fail){fail=false;throw new Error('parse unavailable');}return {source:{id:'same-source'},bucket:'user-evidence',path:'owner/source',token:'signed-private-token'};});const file=new File(['本人原始工作内容'],'record.txt');const progress:EvidenceUploadProgress={};await expect(uploadEvidence(file,{},progress)).rejects.toThrow('parse unavailable');expect(await uploadEvidence(file,{},progress)).toBe('same-source');expect(mocks.upload).toHaveBeenCalledOnce();expect(mocks.request.mock.calls.filter(call=>JSON.parse(call[1].body).action==='upload')).toHaveLength(1);});
it('upload failure retries the original signed upload and unsupported files do not create a source',async()=>{mocks.upload.mockResolvedValueOnce({error:{message:'network failure'}});const file=new File(['original'],'record.md');const progress:EvidenceUploadProgress={};await expect(uploadEvidence(file,{},progress)).rejects.toThrow('文件上传失败');await uploadEvidence(file,{},progress);expect(mocks.upload).toHaveBeenCalledTimes(2);expect(mocks.request.mock.calls.filter(call=>JSON.parse(call[1].body).action==='upload')).toHaveLength(1);const calls=mocks.request.mock.calls.length;await expect(uploadEvidence(new File(['x'],'file.pdf'))).rejects.toThrow('目前支持');expect(mocks.request.mock.calls).toHaveLength(calls);});
