import { BookOpen, Check, Circle, Clock3, Lock, Play, Workflow } from "lucide-react";
import type { CourseGraphData } from "../runtime/courseRuntime";
import type { UserKnowledgeRecord } from "@/features/profile/types";
import { buildCoursePath } from "./coursePath";

export function CoursePathView({ graph, userKnowledge, onSelect, microMinutes }: { graph: CourseGraphData; userKnowledge: UserKnowledgeRecord[]; onSelect(nodeId: string): void; microMinutes?(nodeId:string):number|undefined }) {
  const path = buildCoursePath(graph, userKnowledge);
  const labels = { completed:"已掌握", underway:"进行中", available:"可以开始", blocked:"暂不可用" };
  const grouped = graph.chapters.map((chapter)=>({chapter,items:path.filter((item)=>item.node.chapterId===chapter.id)})).filter((group)=>group.items.length);
  return <section className="course-path" aria-label="课程学习路径"><header className="course-path-header"><span className="atlas-kicker">COURSE PATH</span><h2>沿课程路径向下学习</h2><p>连线只表达课程展示顺序；节点能否开始仍由真实 Knowledge prerequisite 决定。</p></header><div className="course-path-chapters">{grouped.map(({chapter,items},chapterIndex)=><section className="course-path-chapter" key={chapter.id}><header><span>CHAPTER {String(chapterIndex+1).padStart(2,"0")}</span><h3>{chapter.title}</h3><small>{items.length} 个 Knowledge</small></header><div className="course-path-track">{items.map((item,index)=>{const minutes=microMinutes?.(item.node.id);return <button type="button" className={`course-path-node ${item.state} offset-${index%3}`} key={item.node.id} disabled={item.state==="blocked"} onClick={()=>onSelect(item.node.id)}><i>{item.state==="completed"?<Check size={17}/>:item.state==="blocked"?<Lock size={15}/>:item.state==="underway"?<Play size={15}/>:<Circle size={14}/>}</i><span><small>{labels[item.state]} · 第 {item.node.primaryCoverage.lessonOrder} 课</small><strong>{item.node.title}</strong><em>{item.blockedBy.length?`需要先完成：${item.blockedBy.join("、")}`:<>{minutes?<><Clock3 size={12}/>{minutes} min</>:null}{item.node.materialContexts.length?<><BookOpen size={12}/>{item.node.materialContexts.length}</>:null}{item.node.assignmentCount?<><Workflow size={12}/>{item.node.assignmentCount}</>:null}{!minutes&&!item.node.materialContexts.length&&!item.node.assignmentCount?"暂无关联资源":null}</>}</em></span></button>})}</div></section>)}</div></section>;
}
