import { BookOpen, Check, Circle, Clock3, Lock, Play, Workflow } from "lucide-react";
import type { CourseGraphData } from "../runtime/courseRuntime";
import type { UserKnowledgeRecord } from "@/features/profile/types";
import { buildCoursePath } from "./coursePath";

export function CoursePathView({ graph, userKnowledge, onSelect, microMinutes }: { graph: CourseGraphData; userKnowledge: UserKnowledgeRecord[]; onSelect(nodeId: string): void; microMinutes?(nodeId:string):number|undefined }) {
  const path = buildCoursePath(graph, userKnowledge);
  const labels = { completed:"已掌握", learned:"已学完", underway:"进行中", available:"已解锁", blocked:"前置未满足" };
  const grouped = graph.chapters.map((chapter)=>({chapter,items:path.filter((item)=>item.node.chapterId===chapter.id)})).filter((group)=>group.items.length);
  return <section className="course-path" aria-label="课程路线"><header className="course-path-header"><span className="atlas-kicker">课程路线</span><h2>沿课程路线向下学习</h2><p>课程顺序用于展示学习路线；是否已解锁由真实的先修知识和学习进度决定。</p></header><div className="course-path-chapters">{grouped.map(({chapter,items},chapterIndex)=><section className="course-path-chapter" key={chapter.id}><header><span>第 {chapterIndex+1} 章</span><h3>{chapter.title}</h3><small>{items.length} 个知识点</small></header><div className="course-path-track">{items.map((item,index)=>{const minutes=microMinutes?.(item.node.id);return <button type="button" className={`course-path-node ${item.state} offset-${index%3}`} key={item.node.id} disabled={item.state==="blocked"} onClick={()=>onSelect(item.node.id)}><i>{item.state==="completed"||item.state==="learned"?<Check size={17}/>:item.state==="blocked"?<Lock size={15}/>:item.state==="underway"?<Play size={15}/>:<Circle size={14}/>}</i><span><small>{labels[item.state]} · 第 {item.node.lesson} 课</small><strong>{item.node.title}</strong><em>{item.blockedBy.length?`需要先完成：${item.blockedBy.join("、")}`:<>{minutes?<><Clock3 size={12}/>{minutes} 分钟</>:null}{item.node.materialContexts.length?<><BookOpen size={12}/>{item.node.materialContexts.length} 份材料</>:null}{item.node.assignmentCount?<><Workflow size={12}/>{item.node.assignmentCount} 项实训</>:null}{!minutes&&!item.node.materialContexts.length&&!item.node.assignmentCount?"暂无可执行的学习活动":null}</>}</em></span></button>})}</div></section>)}</div></section>;
}
