import { mkdir,writeFile } from "node:fs/promises";
import { join } from "node:path";
import { strFromU8,strToU8,unzipSync,zipSync } from "fflate";

const output=process.argv[2]??"/tmp/eduflow-golden-h5p";await mkdir(output,{recursive:true});
const json=(value:unknown)=>strToU8(JSON.stringify(value));
async function download(url:string){const response=await fetch(url);if(!response.ok)throw new Error(`${url}: ${response.status}`);return new Uint8Array(await response.arrayBuffer());}
async function template(name:string,id:string,mutate:(content:Record<string,unknown>,files:Record<string,Uint8Array>)=>void){const source=`https://h5p.org/sites/default/files/h5p/exports/${name}.h5p`;const files=unzipSync(await download(source));const definition=JSON.parse(strFromU8(files["h5p.json"])) as Record<string,unknown>;const content=JSON.parse(strFromU8(files["content/content.json"])) as Record<string,unknown>;mutate(content,files);definition.title=id;definition.license="CC BY";definition.licenseVersion="4.0";definition.authors=[{name:"H5P Group",role:"Originator"},{name:"EduFlow",role:"Editor"}];definition.source=source;files["h5p.json"]=json(definition);files["content/content.json"]=json(content);await writeFile(join(output,`${id}.h5p`),zipSync(files,{level:6}));}

await template("drag-the-words-1399","golden-h5p-agent-drag-words",(content)=>{content.taskDescription="<p>将组件拖到 Agent 行动循环中的正确职责。</p>";content.textField="*Model* 负责判断下一步动作，*Tool* 执行受控外部动作，*State* 保存循环所需上下文。";content.distractors="*Theme* *Avatar*";content.correctText="组件职责正确";content.incorrectText="检查判断、动作与上下文的边界";});
await template("fill-in-the-blanks-837","golden-h5p-agent-fill-blanks",(content,files)=>{content.text="<p>补全 Agent 行动循环。</p>";content.questions=["Agent 先 *observe/观察* 当前状态，再由 Model *decide/判断* 动作，Tool 执行后必须 *verify/验证* 结果。"];delete content.media;for(const name of Object.keys(files))if(name.startsWith("content/images/"))delete files[name];});
await template("drag-and-drop-712","golden-h5p-workflow-drag-drop",(content,files)=>{const question=content.question as Record<string,any>;question.settings={size:{width:800,height:420},background:{path:"images/workflow-background.svg",mime:"image/svg+xml",width:800,height:420,copyright:{license:"CC0"}}};question.task={elements:["LLM","TOOL","MEMORY"].map((label,index)=>({type:{library:"H5P.AdvancedText 1.1",params:{text:`<p>${label}</p>`},subContentId:`eduflow-element-${index}`,metadata:{title:label,license:"CC0",contentType:"Text"}},x:12+index*28,y:72,width:18,height:10,dropZones:["0","1","2"],backgroundOpacity:100,multiple:false})),dropZones:[{label:"推理 / 决策",correctElements:["0"]},{label:"外部动作",correctElements:["1"]},{label:"跨步骤状态",correctElements:["2"]}].map((zone,index)=>({x:7+index*31,y:14,width:26,height:30,showLabel:true,backgroundOpacity:85,single:true,autoAlign:false,tipsAndFeedback:{tip:"",feedbackOnCorrect:"职责匹配",feedbackOnIncorrect:"重新检查职责边界"},...zone}))};files["content/images/workflow-background.svg"]=strToU8('<svg xmlns="http://www.w3.org/2000/svg" width="800" height="420"><rect width="800" height="420" fill="#f4f7fb"/><path d="M50 210H750" stroke="#d7deea" stroke-width="2"/></svg>');for(const name of Object.keys(files))if(name.startsWith("content/images/")&&!name.endsWith("workflow-background.svg"))delete files[name];});

const embed=await (await fetch("https://h5p.org/h5p/embed/615")).text();const integrationLine=embed.match(/H5PIntegration = (\{.*\});/)?.[1];if(!integrationLine)throw new Error("Question Set integration not found");const integration=JSON.parse(integrationLine) as Record<string,any>;const original=JSON.parse(integration.contents["cid-616"].jsonContent) as Record<string,any>;const seedQuestion=original.questions.find((item:Record<string,unknown>)=>item.library==="H5P.MultiChoice 1.16");if(!seedQuestion)throw new Error("Question Set MultiChoice seed missing");
const prompts=[{question:"<p>瞬时网络错误且操作幂等时，首选什么恢复动作？</p>",answers:[["有界 retry",true],["无限 retry",false],["忽略错误",false]]},{question:"<p>主服务持续不可用，但存在已验证替代服务时，应选择什么？</p>",answers:[["fallback",true],["继续等待且不设超时",false],["伪造成功结果",false]]},{question:"<p>恢复动作执行后，最后必须做什么？</p>",answers:[["验证 outcome",true],["立即删除失败证据",false],["直接标记 mastery",false]]}];
original.passPercentage=100;original.questions=prompts.map((prompt,index)=>{const item=structuredClone(seedQuestion);item.subContentId=`eduflow-recovery-${index}`;item.metadata={title:`Failure Recovery ${index+1}`,license:"CC BY",contentType:"Multiple Choice"};item.params.question=prompt.question;item.params.answers=prompt.answers.map(([text,correct])=>({correct,text:`<div>${text}</div>`,tipsAndFeedback:{tip:"",chosenFeedback:"",notChosenFeedback:""}}));delete item.params.media;item.params.behaviour.randomAnswers=false;return item;});original.endGame.showAnimations=false;original.endGame.showSolutionButton=false;original.override={showSolutionButton:"off",retryButton:"on",checkButton:true};
const assetUrls=[...embed.matchAll(/(?:src|href)="([^"]*\/sites\/default\/files\/h5p\/libraries\/[^"]+)"/g)].map((match)=>new URL(match[1],"https://h5p.org").toString().replace(/&amp;/g,"&"));const scripts=assetUrls.filter((url)=>/\.js(?:\?|$)/.test(url)),styles=assetUrls.filter((url)=>/\.css(?:\?|$)/.test(url));const qFiles:Record<string,Uint8Array>={"content/content.json":json(original)};const localPath=(url:string)=>`vendor/${new URL(url).pathname.split("/libraries/")[1]}`;
for(const url of scripts)qFiles[`H5P.QuestionSet-1.20/${localPath(url)}`]=await download(url);
for(const url of styles){const bytes=await download(url);qFiles[`H5P.QuestionSet-1.20/${localPath(url)}`]=bytes;const css=strFromU8(bytes);for(const match of css.matchAll(/url\(([^)]+)\)/g)){const reference=decodeURIComponent(match[1].trim()).replace(/^["']|["']$/g,"");if(reference.startsWith("data:"))continue;const assetUrl=new URL(reference,url).toString();if(new URL(assetUrl).hostname!=="h5p.org"||!new URL(assetUrl).pathname.includes("/libraries/")||!/\.(?:woff2?|ttf|eot)$/i.test(new URL(assetUrl).pathname))continue;qFiles[`H5P.QuestionSet-1.20/${localPath(assetUrl)}`]=await download(assetUrl);}}
qFiles["H5P.QuestionSet-1.20/library.json"]=json({title:"Question Set",machineName:"H5P.QuestionSet",majorVersion:1,minorVersion:20,patchVersion:31,runnable:1,embedTypes:["div"],preloadedJs:scripts.map((url)=>({path:localPath(url)})),preloadedCss:styles.map((url)=>({path:localPath(url)}))});qFiles["h5p.json"]=json({title:"golden-h5p-recovery-question-set",language:"zh",mainLibrary:"H5P.QuestionSet",embedTypes:["div"],license:"CC BY",licenseVersion:"4.0",authors:[{name:"H5P Group",role:"Originator"},{name:"EduFlow",role:"Editor"}],source:"https://h5p.org/question-set",preloadedDependencies:[{machineName:"H5P.QuestionSet",majorVersion:1,minorVersion:20}]});await writeFile(join(output,"golden-h5p-recovery-question-set.h5p"),zipSync(qFiles,{level:6}));
console.log(`Built four controlled Golden H5P packages in ${output}.`);
