import type { EdgeSeed } from "./types";

/**
 * These manually reviewed relations form the current demo canonical graph and
 * may serve as reference data for future automated relation discovery.
 */
export const agenticAiEdgeSeeds: EdgeSeed[] = [
  ["H03", "H02", "related", 0.55, "Automation systems and workflows both coordinate explicit executable steps."],
  ["H02", "AG01", "related", 0.62, "Agent behavior can be composed with deterministic workflow control."],
  ["P02", "P01", "prerequisite", "soft", "A task environment is normally described relative to the goal pursued within it."],
  ["P03", "P01", "prerequisite", "soft", "Environment boundaries include constraints on available observations and actions."],
  ["P01", "P05", "enables", 0.8, "Observable environment state provides evidence for checking task completion."],
  ["AG01", "A01", "prerequisite", "soft", "Classical agent architecture specializes the general agent concept into concrete parts."],
  ["A01", "A02", "prerequisite", "soft", "Classical perception-decision-action structure grounds comparison with LLM agents."],
  ["A02", "R01", "prerequisite", "soft", "An LLM agent architecture provides the model and state boundary used by a reasoning loop."],
  ["R01", "R10", "enables", 0.9, "ReAct is a concrete reasoning loop that alternates thought, action, and observation."],
  ["R03", "R04", "prerequisite", "hard", "Plan-and-Execute requires an explicit plan before execution can be separated from planning."],
  ["R04", "R11", "prerequisite", "hard", "Monitoring a plan requires an executing plan with expected steps and outcomes."],
  ["R11", "R06", "prerequisite", "hard", "Replanning depends on detecting a meaningful deviation from the current plan."],
  ["R11", "R07", "enables", 0.78, "Plan deviations provide concrete evidence for reflection on execution quality."],
  ["R08", "R09", "prerequisite", "hard", "Evaluator-Optimizer requires an evaluator that produces actionable quality feedback."],
  ["R07", "R09", "enables", 0.76, "Reflection supplies improvement observations that an optimizer can apply iteratively."],
  ["W01", "W02", "enables", 0.8, "Human-in-the-loop participation enables explicit approval checkpoints."],
  ["P03", "W02", "enables", 0.65, "Constraints identify high-risk boundaries at which approval is required."],
  ["C01", "C02", "prerequisite", "soft", "A controlled model invocation needs a defined task and context input."],
  ["C02", "C04", "enables", 0.7, "Model responses provide the primary content transformed into an agent output."],
  ["C03", "RT01", "enables", 0.88, "An autonomous loop needs state that persists observations, actions, and progress."],
  ["I02", "I01", "enables", 0.9, "A schema gives structured output its machine-readable contract."],
  ["I02", "I05", "prerequisite", "hard", "Schema validation requires a schema against which values can be checked."],
  ["I05", "I01", "enables", 0.9, "Validation makes structured output reliable for downstream machine processing."],
  ["I04", "C02", "enables", 0.8, "Context engineering prepares the instructions and evidence supplied to model invocation."],
  ["T11", "T12", "enables", 0.9, "Function calling expresses requests against a discoverable tool interface."],
  ["T11", "T03", "prerequisite", "soft", "Tool selection depends on understanding each candidate tool's interface and purpose."],
  ["T03", "T14", "enables", 0.8, "Selecting a tool determines the argument contract that must be populated."],
  ["T14", "T15", "prerequisite", "hard", "A tool cannot be invoked correctly without valid arguments for its interface."],
  ["T15", "T06", "prerequisite", "hard", "A tool result exists only after an attempted tool execution."],
  ["T07", "T08", "prerequisite", "hard", "Retry policy must first distinguish recoverable tool failures from terminal failures."],
  ["T09", "T10", "enables", 0.75, "Tool permission boundaries identify actions that require explicit approval."],
  ["W02", "T10", "enables", 0.85, "An approval gate supplies the human decision point for a risky tool action."],
  ["T06", "RT01", "enables", 0.7, "Tool results become observations that allow the agent loop to continue."],
  ["K01", "K12", "prerequisite", "hard", "Content must be parsed before it can be split into retrievable chunks."],
  ["K12", "K13", "enables", 0.82, "Semantic chunks provide bounded units for embedding."],
  ["K13", "K14", "enables", 0.9, "Embeddings provide similarity representations used for retrieval."],
  ["K14", "K15", "prerequisite", "soft", "Reranking operates on candidates returned by retrieval."],
  ["K15", "K16", "enables", 0.8, "Ranked source passages make citations more relevant and traceable."],
  ["K04", "K05", "related", 0.68, "Working state and long-term memory differ in lifetime but share state persistence concerns."],
  ["RT01", "RT02", "related", 0.72, "An agent loop is commonly governed by an explicit task state machine."],
  ["RT02", "RT03", "enables", 0.62, "Task states provide places to enforce step, time, and resource limits."],
  ["RT03", "RT14", "enables", 0.78, "Bounded runtime failures can trigger controlled recovery instead of unbounded execution."],
  ["RT02", "RT15", "enables", 0.85, "A task state model identifies the state that a checkpoint must preserve."],
  ["RT15", "RT06", "enables", 0.88, "Checkpoint events contribute traceable state snapshots to the audit trail."],
  ["W13", "W04", "enables", 0.9, "An orchestrator defines and dispatches bounded tasks to workers."],
  ["W13", "WF03", "enables", 0.9, "Orchestrator behavior supplies the coordination half of an orchestrator-worker workflow."],
  ["W04", "WF03", "enables", 0.9, "Worker execution supplies the delegated work half of an orchestrator-worker workflow."],
  ["WF03", "WF05", "related", 0.7, "Orchestrator-worker is one reusable topology for an agentic workflow."],
  ["MA02", "MA12", "enables", 0.84, "A supervisor provides centralized routing for multi-agent delegation."],
  ["MA03", "MA04", "related", 0.64, "A skill can package instructions for using one or more tools."],
  ["MA04", "MA15", "related", 0.7, "Plugins commonly bundle reusable skills with tools and integrations."],
  ["MA03", "MA06", "related", 0.74, "MCP standardizes discovery and invocation of tool-like capabilities."],
  ["MA07", "MA12", "enables", 0.7, "Agent-to-Agent protocols enable delegation across remote agent boundaries."],
  ["E12", "E13", "enables", 0.88, "Benchmark tasks provide repeatable inputs and criteria for outcome evaluation."],
  ["E12", "E14", "enables", 0.82, "Benchmark tasks provide comparable trajectories for process evaluation."],
  ["E13", "E05", "enables", 0.86, "Repeatable outcome scores allow regression tests to detect quality loss."],
  ["E14", "E05", "enables", 0.74, "Trajectory checks let regression tests detect behavioral changes before final output."],
  ["E06", "E07", "enables", 0.9, "Logs, metrics, and traces provide the evidence used in runtime debugging."],
  ["S01", "S02", "related", 0.62, "Sandboxing is one enforcement mechanism for system guardrails."],
  ["S01", "S03", "related", 0.72, "Least privilege is a core policy used to implement action guardrails."],
  ["S14", "S15", "related", 0.66, "An API service commonly persists agent and business state in a database."],
  ["S06", "S07", "prerequisite", "hard", "A queue worker requires a task queue from which to receive work."],
  ["S14", "S08", "enables", 0.72, "A stable API service is an executable unit that can be deployed."],
  ["S15", "S08", "enables", 0.7, "Production deployment requires a persistence design for durable state."],
  ["S07", "S08", "enables", 0.76, "Queue workers are runtime units that must be deployed with the service."],

  ["P02", "P05", "enables", 0.94, "A completion condition operationalizes the goal into checkable success criteria."],
  ["P03", "P05", "enables", 0.84, "Completion must be checked without violating the task's constraints."],
  ["P01", "A01", "prerequisite", "soft", "Classical agent architecture is defined by how an agent perceives and acts in an environment."],
  ["AG01", "C01", "enables", 0.78, "The agent contract determines what task and context input an agent accepts."],
  ["A02", "C02", "enables", 0.9, "Model invocation is a direct runtime component of an LLM agent architecture."],
  ["A02", "C03", "enables", 0.86, "LLM agent architecture requires explicit state across model and tool turns."],
  ["A02", "T11", "enables", 0.88, "Tool interfaces provide the external action capability of an LLM agent."],
  ["A02", "I04", "enables", 0.84, "Context engineering supplies the information boundary around the model component."],
  ["C02", "R01", "related", 0.82, "Model invocations implement the reasoning steps inside an LLM reasoning loop."],
  ["R01", "R03", "related", 0.86, "Planning structures multi-step decisions inside an agent reasoning process."],
  ["R03", "R11", "enables", 0.91, "An explicit plan provides expected steps that can be monitored during execution."],
  ["R08", "R07", "enables", 0.82, "Evaluation feedback gives reflection concrete evidence about what should improve."],
  ["R08", "E13", "enables", 0.87, "Evaluator criteria can be applied directly to judge final outcomes."],
  ["R08", "E14", "enables", 0.9, "An evaluator can score reasoning, planning, and tool-use trajectories."],
  ["E14", "R07", "related", 0.84, "Trajectory evaluation and reflection form a feedback relationship around execution quality."],
  ["R10", "T03", "enables", 0.9, "The Act step in ReAct requires selecting an appropriate tool or action."],
  ["T06", "R01", "related", 0.88, "Tool results are observations consumed by the next reasoning step in a feedback loop."],
  ["T12", "T14", "enables", 0.92, "Function-calling protocols carry structured arguments for the chosen tool."],
  ["T15", "T07", "enables", 0.9, "Execution exposes concrete parameter, permission, timeout, and runtime failures."],
  ["T08", "RT14", "enables", 0.82, "Bounded tool retries are one direct recovery strategy for transient runtime failure."],
  ["T10", "W01", "related", 0.85, "Tool approval is a concrete human-in-the-loop interaction at an action boundary."],
  ["S03", "T09", "related", 0.92, "Least privilege determines the resources and actions exposed through tool permissions."],
  ["S02", "T15", "related", 0.82, "A sandbox constrains side effects while tools execute external code or actions."],
  ["S01", "W02", "related", 0.78, "Guardrails identify risky decisions that should pass through an approval gate."],
  ["I01", "C04", "enables", 0.88, "Structured output makes the agent's output contract machine-readable and dependable."],
  ["C03", "K04", "enables", 0.9, "Working state is the task-scoped portion of the broader agent state."],
  ["K04", "I04", "related", 0.82, "Working state is a direct source selected during context engineering."],
  ["K05", "I04", "related", 0.85, "Long-term memory is a direct source selected during context engineering."],
  ["K14", "I04", "related", 0.86, "Retrieved evidence is selected and organized through context engineering."],
  ["K16", "C04", "related", 0.76, "Citations make agent outputs traceable to retrieved source material."],
  ["R01", "RT01", "enables", 0.92, "A reasoning loop supplies the think-act-observe cycle executed by an agent runtime loop."],
  ["RT01", "T15", "related", 0.91, "The agent loop and tool execution participate in a repeated action-observation feedback cycle."],
  ["RT01", "R08", "related", 0.78, "Runtime loops produce outputs and trajectories that evaluators inspect in a feedback cycle."],
  ["RT15", "RT14", "enables", 0.84, "A checkpoint provides the saved state needed to resume after runtime failure."],
  ["RT06", "E06", "enables", 0.88, "An audit trail supplies structured events for logs, metrics, and traces."],
  ["E06", "E14", "enables", 0.82, "Observability captures the intermediate execution evidence used for trajectory evaluation."],
  ["H02", "WF05", "enables", 0.84, "Workflow control provides deterministic structure around agent decisions and approvals."],
  ["A02", "WF05", "enables", 0.86, "LLM agent components supply the adaptive decision steps in an agentic workflow."],
  ["R09", "WF05", "enables", 0.78, "Evaluator-Optimizer loops provide iterative quality control inside agentic workflows."],
  ["WF05", "W02", "related", 0.74, "Agentic workflows commonly include approval gates at high-risk transitions."],
  ["W13", "MA02", "related", 0.82, "Orchestrators and supervisors both coordinate delegated work and integrate results."],
  ["MA12", "WF03", "enables", 0.87, "Multi-agent delegation supplies the task routing used by orchestrator-worker workflows."],
  ["MA03", "T11", "related", 0.9, "A tool becomes callable by an agent through an explicit tool interface."],
  ["MA04", "T11", "related", 0.78, "A skill can expose or prescribe the tool interfaces needed for its workflow."],
  ["MA06", "T11", "related", 0.88, "MCP provides standardized discovery and invocation of tool interfaces."],
  ["MA15", "MA06", "related", 0.76, "A plugin may package an MCP integration alongside skills and tools."],
  ["MA07", "WF03", "enables", 0.75, "Agent-to-Agent communication enables orchestrators to coordinate remote workers."],
  ["S06", "W04", "related", 0.78, "A task queue transports bounded work items to workers."],
  ["S06", "RT02", "related", 0.72, "Queued tasks require explicit lifecycle states for dispatch, running, retry, and completion."],
  ["C04", "S14", "enables", 0.72, "A stable agent output contract can be exposed through an API service response."],
  ["S15", "C03", "related", 0.82, "Database persistence stores the durable portions of agent state across runs."]
];
